<Type Name="Exception" FullName="System.Exception">
  <Metadata><Meta Name="ms.openlocfilehash" Value="849d30aa85e6c854b68c1ba21c0d2b2f5b5886ce" /><Meta Name="ms.sourcegitcommit" Value="c0c07dbd19cd7017243f9ac36915755f79bc8da6" /><Meta Name="ms.translationtype" Value="HT" /><Meta Name="ms.contentlocale" Value="zh-CN" /><Meta Name="ms.lasthandoff" Value="11/27/2018" /><Meta Name="ms.locfileid" Value="52385597" /></Metadata><TypeSignature Language="C#" Value="public class Exception : System.Runtime.InteropServices._Exception, System.Runtime.Serialization.ISerializable" />
  <TypeSignature Language="ILAsm" Value=".class public sequential ansi serializable beforefieldinit Exception extends System.Object implements class System.Runtime.InteropServices._Exception, class System.Runtime.Serialization.ISerializable" />
  <TypeSignature Language="DocId" Value="T:System.Exception" />
  <TypeSignature Language="VB.NET" Value="Public Class Exception&#xA;Implements _Exception, ISerializable" />
  <TypeSignature Language="C++ CLI" Value="public ref class Exception : System::Runtime::InteropServices::_Exception, System::Runtime::Serialization::ISerializable" />
  <TypeSignature Language="F#" Value="type Exception = class&#xA;    interface ISerializable&#xA;    interface _Exception" />
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.10.0</AssemblyVersion>
    <AssemblyVersion>4.0.20.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>1.0.5000.0</AssemblyVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Object</BaseTypeName>
  </Base>
  <Interfaces>
    <Interface>
      <InterfaceName>System.Runtime.InteropServices._Exception</InterfaceName>
    </Interface>
    <Interface>
      <InterfaceName>System.Runtime.Serialization.ISerializable</InterfaceName>
    </Interface>
  </Interfaces>
  <Attributes>
    <Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)</AttributeName>
    </Attribute>
    <Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>System.Runtime.InteropServices.ComDefaultInterface(typeof(System.Runtime.InteropServices._Exception))</AttributeName>
    </Attribute>
    <Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
    <Attribute FrameworkAlternate="netframework-1.1">
      <AttributeName>System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.AutoDual)</AttributeName>
    </Attribute>
    <Attribute FrameworkAlternate="netframework-1.1;netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0">
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary><span data-ttu-id="cf328-101">表示在应用程序执行过程中发生的错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-101">Represents errors that occur during application execution.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-102">此类是所有异常的基类。</span><span class="sxs-lookup"><span data-stu-id="cf328-102">This class is the base class for all exceptions.</span></span> <span data-ttu-id="cf328-103">出现错误时，系统或当前正在执行的应用程序报告它通过引发异常，其中包含有关错误的信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-103">When an error occurs, either the system or the currently executing application reports it by throwing an exception that contains information about the error.</span></span> <span data-ttu-id="cf328-104">引发异常后，它是由应用程序或默认异常处理程序进行处理。</span><span class="sxs-lookup"><span data-stu-id="cf328-104">After an exception is thrown, it is handled by the application or by the default exception handler.</span></span>  
  
 <span data-ttu-id="cf328-105">本节内容：</span><span class="sxs-lookup"><span data-stu-id="cf328-105">In this section:</span></span>  
  
 <span data-ttu-id="cf328-106">[错误和异常](#Errors) </span><span class="sxs-lookup"><span data-stu-id="cf328-106">[Errors and exceptions](#Errors) </span></span>  
 <span data-ttu-id="cf328-107">[Try/catch 块](#TryCatch) </span><span class="sxs-lookup"><span data-stu-id="cf328-107">[Try/catch blocks](#TryCatch) </span></span>  
 <span data-ttu-id="cf328-108">[异常类型的功能](#Features) </span><span class="sxs-lookup"><span data-stu-id="cf328-108">[Exception type features](#Features) </span></span>  
 <span data-ttu-id="cf328-109">[异常类属性](#Properties) </span><span class="sxs-lookup"><span data-stu-id="cf328-109">[Exception class properties](#Properties) </span></span>  
 <span data-ttu-id="cf328-110">[性能注意事项](#Performance) </span><span class="sxs-lookup"><span data-stu-id="cf328-110">[Performance considerations](#Performance) </span></span>  
 <span data-ttu-id="cf328-111">[重新引发异常](#Rethrow) </span><span class="sxs-lookup"><span data-stu-id="cf328-111">[Re-throwing an exception](#Rethrow) </span></span>  
 <span data-ttu-id="cf328-112">[选择标准异常](#Standard) </span><span class="sxs-lookup"><span data-stu-id="cf328-112">[Choosing standard exceptions](#Standard) </span></span>  
 [<span data-ttu-id="cf328-113">实现自定义异常</span><span class="sxs-lookup"><span data-stu-id="cf328-113">Implementing custom exceptions</span></span>](#Custom)  
  
<a name="Errors"></a>   
## <a name="errors-and-exceptions"></a><span data-ttu-id="cf328-114">错误和异常</span><span class="sxs-lookup"><span data-stu-id="cf328-114">Errors and exceptions</span></span>  
 <span data-ttu-id="cf328-115">运行时错误可能的原因有多种。</span><span class="sxs-lookup"><span data-stu-id="cf328-115">Run-time errors can occur for a variety of reasons.</span></span> <span data-ttu-id="cf328-116">但是，并非所有错误应作为在代码中的异常都处理。</span><span class="sxs-lookup"><span data-stu-id="cf328-116">However, not all errors should be handled as exceptions in your code.</span></span> <span data-ttu-id="cf328-117">以下是一些可以发生在运行的时和适当的方式对其进行响应的错误类别。</span><span class="sxs-lookup"><span data-stu-id="cf328-117">Here are some categories of errors that can occur at run time and the appropriate ways to respond to them.</span></span>  
  
-   <span data-ttu-id="cf328-118">**用法错误。**</span><span class="sxs-lookup"><span data-stu-id="cf328-118">**Usage errors.**</span></span> <span data-ttu-id="cf328-119">用法错误表示可能会导致异常的程序逻辑中的错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-119">A usage error represents an error in program logic that can result in an exception.</span></span> <span data-ttu-id="cf328-120">但是，不能通过异常处理，但通过修改了错误代码，则应解决该错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-120">However, the error should be addressed not through exception handling but by modifying the faulty code.</span></span> <span data-ttu-id="cf328-121">例如的重写<xref:System.Object.Equals%28System.Object%29?displayProperty=nameWithType>方法在下面的示例假设`obj`参数必须始终为非 null。</span><span class="sxs-lookup"><span data-stu-id="cf328-121">For example, the override of the <xref:System.Object.Equals%28System.Object%29?displayProperty=nameWithType> method in the following example assumes that the `obj` argument must always be non-null.</span></span>  
  
     [!code-csharp[System.Exception.Class#4](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/usageerrors1.cs#4)]
     [!code-vb[System.Exception.Class#4](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/usageerrors1.vb#4)]  
  
     <span data-ttu-id="cf328-122"><xref:System.NullReferenceException>产生的异常时`obj`是`null`可通过修改源代码，以显式测试是否为 null 之前，调用来消除<xref:System.Object.Equals%2A?displayProperty=nameWithType>重写和重新编译。</span><span class="sxs-lookup"><span data-stu-id="cf328-122">The <xref:System.NullReferenceException> exception that results when `obj` is `null` can be eliminated by modifying the source code to explicitly test for null before calling the <xref:System.Object.Equals%2A?displayProperty=nameWithType> override and then re-compiling.</span></span> <span data-ttu-id="cf328-123">下面的示例包含更正的源代码处理`null`参数。</span><span class="sxs-lookup"><span data-stu-id="cf328-123">The following example contains the corrected source code that handles a `null` argument.</span></span>  
  
     [!code-csharp[System.Exception.Class#5](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/usageerrors2.cs#5)]
     [!code-vb[System.Exception.Class#5](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/usageerrors2.vb#5)]  
  
     <span data-ttu-id="cf328-124">而不是使用异常处理的使用情况的错误，可以使用<xref:System.Diagnostics.Debug.Assert%2A?displayProperty=nameWithType>的方法来确定在调试版本中的用法错误和<xref:System.Diagnostics.Trace.Assert%2A?displayProperty=nameWithType>的方法来确定在调试和发布中的用法错误生成。</span><span class="sxs-lookup"><span data-stu-id="cf328-124">Instead of using exception handling for usage errors, you can use the <xref:System.Diagnostics.Debug.Assert%2A?displayProperty=nameWithType> method to identify usage errors in debug builds, and the <xref:System.Diagnostics.Trace.Assert%2A?displayProperty=nameWithType> method to identify usage errors in both debug and release builds.</span></span> <span data-ttu-id="cf328-125">有关详细信息，请参阅[托管代码中的断言](/visualstudio/debugger/assertions-in-managed-code)。</span><span class="sxs-lookup"><span data-stu-id="cf328-125">For more information, see [Assertions in Managed Code](/visualstudio/debugger/assertions-in-managed-code).</span></span>  
  
-   <span data-ttu-id="cf328-126">**程序错误数。**</span><span class="sxs-lookup"><span data-stu-id="cf328-126">**Program errors.**</span></span> <span data-ttu-id="cf328-127">程序错误是一定不能通过编写无 bug 的代码来避免运行时错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-127">A program error is a run-time error that cannot necessarily be avoided by writing bug-free code.</span></span>  
  
     <span data-ttu-id="cf328-128">在某些情况下，程序错误可能会反映预期或例程错误条件。</span><span class="sxs-lookup"><span data-stu-id="cf328-128">In some cases, a program error may reflect an expected or routine error condition.</span></span> <span data-ttu-id="cf328-129">在这种情况下，你可能想要避免使用异常处理程序错误处理，而是重试该操作。</span><span class="sxs-lookup"><span data-stu-id="cf328-129">In this case, you may want to avoid using exception handling to deal with the program error and instead retry the operation.</span></span> <span data-ttu-id="cf328-130">例如，如果用户需要输入以特定格式的日期，您可以分析日期字符串通过调用<xref:System.DateTime.TryParseExact%2A?displayProperty=nameWithType>方法，它返回<xref:System.Boolean>值，该值指示是否分析操作成功，而不是使用<xref:System.DateTime.ParseExact%2A?displayProperty=nameWithType>方法，将引发<xref:System.FormatException>异常，如果日期字符串无法转换为<xref:System.DateTime>值。</span><span class="sxs-lookup"><span data-stu-id="cf328-130">For example, if the user is expected to input a date in a particular format, you can parse the date string by calling the <xref:System.DateTime.TryParseExact%2A?displayProperty=nameWithType> method, which returns a <xref:System.Boolean> value that indicates whether the parse operation succeeded, instead of using the <xref:System.DateTime.ParseExact%2A?displayProperty=nameWithType> method, which throws a <xref:System.FormatException> exception if the date string cannot be converted to a <xref:System.DateTime> value.</span></span> <span data-ttu-id="cf328-131">同样，如果用户尝试打开的文件不存在，则可以首先调用<xref:System.IO.File.Exists%2A?displayProperty=nameWithType>方法来检查文件是否存在并，如果不是，提示用户是否要创建它。</span><span class="sxs-lookup"><span data-stu-id="cf328-131">Similarly, if a user tries to open a file that does not exist, you can first call the <xref:System.IO.File.Exists%2A?displayProperty=nameWithType> method to check whether the file exists and, if it does not, prompt the user whether he or she wants to create it.</span></span>  
  
     <span data-ttu-id="cf328-132">在其他情况下，程序错误反映了可以在代码中处理的异常的错误条件。</span><span class="sxs-lookup"><span data-stu-id="cf328-132">In other cases, a program error reflects an unexpected error condition that can be handled in your code.</span></span> <span data-ttu-id="cf328-133">例如，即使检查以确保存在的文件，它可能会删除之前您可以打开它，也可能已损坏。</span><span class="sxs-lookup"><span data-stu-id="cf328-133">For example, even if you've checked to ensure that a file exists, it may be deleted before you can open it, or it may be corrupted.</span></span> <span data-ttu-id="cf328-134">在这种情况下，尝试打开该文件通过实例化<xref:System.IO.StreamReader>对象或调用<xref:System.IO.File.Open%2A>方法可能会引发<xref:System.IO.FileNotFoundException>异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-134">In that case, trying to open the file by instantiating a <xref:System.IO.StreamReader> object or calling the <xref:System.IO.File.Open%2A> method may throw a <xref:System.IO.FileNotFoundException> exception.</span></span> <span data-ttu-id="cf328-135">在这些情况下，应使用异常处理从错误中恢复。</span><span class="sxs-lookup"><span data-stu-id="cf328-135">In these cases, you should use exception handling to recover from the error.</span></span>  
  
-   <span data-ttu-id="cf328-136">**系统故障。**</span><span class="sxs-lookup"><span data-stu-id="cf328-136">**System failures.**</span></span> <span data-ttu-id="cf328-137">在系统出现故障是不能以编程方式处理有意义的方式在运行时错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-137">A system failure is a run-time error that cannot be handled programmatically in a meaningful way.</span></span> <span data-ttu-id="cf328-138">例如，可能会引发任何方法<xref:System.OutOfMemoryException>异常如果公共语言运行时无法分配更多内存。</span><span class="sxs-lookup"><span data-stu-id="cf328-138">For example, any method can throw an <xref:System.OutOfMemoryException> exception if the common language runtime is unable to allocate additional memory.</span></span> <span data-ttu-id="cf328-139">通常，通过使用异常处理不处理系统故障。</span><span class="sxs-lookup"><span data-stu-id="cf328-139">Ordinarily, system failures are not handled by using exception handling.</span></span> <span data-ttu-id="cf328-140">相反，您可能能够使用如下所示事件<xref:System.AppDomain.UnhandledException?displayProperty=nameWithType>，并调用<xref:System.Environment.FailFast%2A?displayProperty=nameWithType>方法来记录异常信息，并在应用程序终止之前通知失败的用户。</span><span class="sxs-lookup"><span data-stu-id="cf328-140">Instead, you may be able to use an event such as <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> and call the <xref:System.Environment.FailFast%2A?displayProperty=nameWithType> method to log exception information and notify the user of the failure before the application terminates.</span></span>  
  
<a name="TryCatch"></a>   
## <a name="trycatch-blocks"></a><span data-ttu-id="cf328-141">Try/catch 块</span><span class="sxs-lookup"><span data-stu-id="cf328-141">Try/catch blocks</span></span>  
 <span data-ttu-id="cf328-142">公共语言运行时提供了一个异常处理模型，基于异常对象，作为表示形式和程序代码和异常处理代码的分离`try`块和`catch`块。</span><span class="sxs-lookup"><span data-stu-id="cf328-142">The common language runtime provides an exception handling model that is based on the representation of exceptions as objects, and the separation of program code and exception handling code into `try` blocks and `catch` blocks.</span></span> <span data-ttu-id="cf328-143">可以有一个或多个`catch`阻止，每个设计为处理特定类型的异常，或者将一个块可捕获更具体的异常比另一个块。</span><span class="sxs-lookup"><span data-stu-id="cf328-143">There can be one or more `catch` blocks, each designed to handle a particular type of exception, or one block designed to catch a more specific exception than another block.</span></span>  
  
 <span data-ttu-id="cf328-144">如果应用程序处理的应用程序代码块的执行过程中发生的异常，该代码必须位于`try`语句和称为`try`块。</span><span class="sxs-lookup"><span data-stu-id="cf328-144">If an application handles exceptions that occur during the execution of a block of application code, the code must be placed within a `try` statement and is called a `try` block.</span></span> <span data-ttu-id="cf328-145">应用程序代码处理引发的异常`try`块放在`catch`语句，称为`catch`块。</span><span class="sxs-lookup"><span data-stu-id="cf328-145">Application code that handles exceptions thrown by a `try` block is placed within a `catch` statement and is called a `catch` block.</span></span> <span data-ttu-id="cf328-146">零个或多`catch`块下与相关联`try`块中，并且每个`catch`块包含类型筛选器，用于确定它处理的异常的类型。</span><span class="sxs-lookup"><span data-stu-id="cf328-146">Zero or more `catch` blocks are associated with a `try` block, and each `catch` block includes a type filter that determines the types of exceptions it handles.</span></span>  
  
 <span data-ttu-id="cf328-147">在异常发生时`try`块中，系统将搜索关联`catch`它们出现在应用程序代码中，直到它找到的顺序中的块，`catch`块处理异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-147">When an exception occurs in a `try` block, the system searches the associated `catch` blocks in the order they appear in application code, until it locates a `catch` block that handles the exception.</span></span> <span data-ttu-id="cf328-148">一个`catch`块处理类型的异常`T`如果 catch 块的类型筛选器指定`T`或任何类型的`T`派生。</span><span class="sxs-lookup"><span data-stu-id="cf328-148">A `catch` block handles an exception of type `T` if the type filter of the catch block specifies `T` or any type that `T` derives from.</span></span> <span data-ttu-id="cf328-149">系统会停止搜索后查找第一个`catch`块处理异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-149">The system stops searching after it finds the first `catch` block that handles the exception.</span></span> <span data-ttu-id="cf328-150">出于此原因，在应用程序代码中，`catch`之前，必须指定处理类型的块`catch`处理其基类型，如本节后面的示例中所示的块。</span><span class="sxs-lookup"><span data-stu-id="cf328-150">For this reason, in application code, a `catch` block that handles a type must be specified before a `catch` block that handles its base types, as demonstrated in the example that follows this section.</span></span> <span data-ttu-id="cf328-151">处理的 catch 块`System.Exception`最后指定。</span><span class="sxs-lookup"><span data-stu-id="cf328-151">A catch block that handles `System.Exception` is specified last.</span></span>  
  
 <span data-ttu-id="cf328-152">如果没有`catch`与当前相关联的块`try`块处理异常，并且当前`try`块嵌套在其他`try`在当前调用中，将阻止`catch`块与下一步封闭`try`块中搜索。</span><span class="sxs-lookup"><span data-stu-id="cf328-152">If none of the `catch` blocks associated with the current `try` block handle the exception, and the current `try` block is nested within other `try` blocks in the current call, the `catch` blocks associated with the next enclosing `try` block are searched.</span></span> <span data-ttu-id="cf328-153">如果没有`catch`找到异常块中，系统将在当前调用中搜索前面的嵌套级别。</span><span class="sxs-lookup"><span data-stu-id="cf328-153">If no `catch` block for the exception is found, the system searches previous nesting levels in the current call.</span></span> <span data-ttu-id="cf328-154">如果没有`catch`阻止的当前调用中找到的异常、 调用堆栈中向上传递的异常和上一个堆栈帧中搜索`catch`块处理异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-154">If no `catch` block for the exception is found in the current call, the exception is passed up the call stack, and the previous stack frame is searched for a `catch` block that handles the exception.</span></span> <span data-ttu-id="cf328-155">调用堆栈的搜索继续，直到处理该异常或没有更多框架位于调用堆栈。</span><span class="sxs-lookup"><span data-stu-id="cf328-155">The search of the call stack continues until the exception is handled or until no more frames exist on the call stack.</span></span> <span data-ttu-id="cf328-156">如果调用堆栈的顶部访问而无需查找`catch`处理异常，默认异常处理程序块对其进行处理并在应用程序终止。</span><span class="sxs-lookup"><span data-stu-id="cf328-156">If the top of the call stack is reached without finding a `catch` block that handles the exception, the default exception handler handles it and the application terminates.</span></span>  
  
<a name="Features"></a>   
## <a name="exception-type-features"></a><span data-ttu-id="cf328-157">异常类型的功能</span><span class="sxs-lookup"><span data-stu-id="cf328-157">Exception type features</span></span>  
 <span data-ttu-id="cf328-158">异常类型支持以下功能：</span><span class="sxs-lookup"><span data-stu-id="cf328-158">Exception types support the following features:</span></span>  
  
-   <span data-ttu-id="cf328-159">描述错误的用户可读文本。</span><span class="sxs-lookup"><span data-stu-id="cf328-159">Human-readable text that describes the error.</span></span> <span data-ttu-id="cf328-160">异常发生时，运行时使可用以通知用户错误的性质，并建议操作文本消息来解决此问题。</span><span class="sxs-lookup"><span data-stu-id="cf328-160">When an exception occurs, the runtime makes a text message available to inform the user of the nature of the error and to suggest action to resolve the problem.</span></span> <span data-ttu-id="cf328-161">此文本消息保存在<xref:System.Exception.Message%2A>异常对象的属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-161">This text message is held in the <xref:System.Exception.Message%2A> property of the exception object.</span></span> <span data-ttu-id="cf328-162">异常对象期间，可以将文本字符串传递给构造函数来描述该特定异常的详细信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-162">During the creation of the exception object, you can pass a text string to the constructor to describe the details of that particular exception.</span></span> <span data-ttu-id="cf328-163">如果没有错误消息参数提供给构造函数，则使用默认错误消息。</span><span class="sxs-lookup"><span data-stu-id="cf328-163">If no error message argument is supplied to the constructor, the default error message is used.</span></span> <span data-ttu-id="cf328-164">有关更多信息，请参见 <xref:System.Exception.Message%2A> 属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-164">For more information, see the <xref:System.Exception.Message%2A> property.</span></span>  
  
-   <span data-ttu-id="cf328-165">调用堆栈时引发异常的状态。</span><span class="sxs-lookup"><span data-stu-id="cf328-165">The state of the call stack when the exception was thrown.</span></span> <span data-ttu-id="cf328-166"><xref:System.Exception.StackTrace%2A>属性包含可用于确定在代码中发生错误的堆栈跟踪。</span><span class="sxs-lookup"><span data-stu-id="cf328-166">The <xref:System.Exception.StackTrace%2A> property carries a stack trace that can be used to determine where the error occurs in the code.</span></span> <span data-ttu-id="cf328-167">堆栈跟踪列出了所有调用的方法和源文件位置的调用中的行号。</span><span class="sxs-lookup"><span data-stu-id="cf328-167">The stack trace lists all the called methods and the line numbers in the source file where the calls are made.</span></span>  
  
<a name="Properties"></a>   
## <a name="exception-class-properties"></a><span data-ttu-id="cf328-168">异常类属性</span><span class="sxs-lookup"><span data-stu-id="cf328-168">Exception class properties</span></span>  
 <span data-ttu-id="cf328-169"><xref:System.Exception>类还包含一些属性，可帮助识别代码位置、 类型、 帮助文件和异常的原因： <xref:System.Exception.StackTrace%2A>， <xref:System.Exception.InnerException%2A>， <xref:System.Exception.Message%2A>， <xref:System.Exception.HelpLink%2A>， <xref:System.Exception.HResult%2A>， <xref:System.Exception.Source%2A>，<xref:System.Exception.TargetSite%2A>，和<xref:System.Exception.Data%2A>。</span><span class="sxs-lookup"><span data-stu-id="cf328-169">The <xref:System.Exception> class includes a number of properties that help identify the code location, the type, the help file, and the reason for the exception: <xref:System.Exception.StackTrace%2A>, <xref:System.Exception.InnerException%2A>, <xref:System.Exception.Message%2A>, <xref:System.Exception.HelpLink%2A>, <xref:System.Exception.HResult%2A>, <xref:System.Exception.Source%2A>, <xref:System.Exception.TargetSite%2A>, and <xref:System.Exception.Data%2A>.</span></span>  
  
 <span data-ttu-id="cf328-170">当两个或多个异常之间存在因果关系<xref:System.Exception.InnerException%2A>属性维护此信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-170">When a causal relationship exists between two or more exceptions, the <xref:System.Exception.InnerException%2A> property maintains this information.</span></span> <span data-ttu-id="cf328-171">外部异常引发响应此内部异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-171">The outer exception is thrown in response to this inner exception.</span></span> <span data-ttu-id="cf328-172">处理外部异常的代码可以使用来自前面的内部异常的信息更恰当地处理错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-172">The code that handles the outer exception can use the information from the earlier inner exception to handle the error more appropriately.</span></span> <span data-ttu-id="cf328-173">有关异常的补充信息可以存储为集合中的键/值对的<xref:System.Exception.Data%2A>属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-173">Supplementary information about the exception can be stored as a collection of key/value pairs in the <xref:System.Exception.Data%2A> property.</span></span>  
  
 <span data-ttu-id="cf328-174">在异常对象的创建过程传递给构造函数的错误消息字符串应本地化，并通过使用可以从资源文件中提供<xref:System.Resources.ResourceManager>类。</span><span class="sxs-lookup"><span data-stu-id="cf328-174">The error message string that is passed to the constructor during the creation of the exception object should be localized and can be supplied from a resource file by using the <xref:System.Resources.ResourceManager> class.</span></span> <span data-ttu-id="cf328-175">本地化资源的详细信息，请参阅[创建附属程序集](~/docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md)并[打包和部署资源](~/docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md)主题。</span><span class="sxs-lookup"><span data-stu-id="cf328-175">For more information about localized resources, see the [Creating Satellite Assemblies](~/docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md) and [Packaging and Deploying Resources](~/docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md) topics.</span></span>  
  
 <span data-ttu-id="cf328-176">若要向用户提供有关异常的发生原因的大量信息<xref:System.Exception.HelpLink%2A>属性可以包含到帮助文件的 URL （或 URN）。</span><span class="sxs-lookup"><span data-stu-id="cf328-176">To provide the user with extensive information about why the exception occurred, the <xref:System.Exception.HelpLink%2A> property can hold a URL (or URN) to a help file.</span></span>  
  
 <span data-ttu-id="cf328-177"><xref:System.Exception>类使用 HRESULT COR_E_EXCEPTION，其值 0x80131500。</span><span class="sxs-lookup"><span data-stu-id="cf328-177">The <xref:System.Exception> class uses the HRESULT COR_E_EXCEPTION, which has the value 0x80131500.</span></span>  
  
 <span data-ttu-id="cf328-178">有关实例的初始属性值的列表<xref:System.Exception>类，请参阅<xref:System.Exception.%23ctor%2A>构造函数。</span><span class="sxs-lookup"><span data-stu-id="cf328-178">For a list of initial property values for an instance of the <xref:System.Exception> class, see the <xref:System.Exception.%23ctor%2A> constructors.</span></span>  
  
<a name="Performance"></a>   
## <a name="performance-considerations"></a><span data-ttu-id="cf328-179">性能注意事项</span><span class="sxs-lookup"><span data-stu-id="cf328-179">Performance considerations</span></span>  
 <span data-ttu-id="cf328-180">引发或处理的异常会消耗大量系统资源和执行时间。</span><span class="sxs-lookup"><span data-stu-id="cf328-180">Throwing or handling an exception consumes a significant amount of system resources and execution time.</span></span> <span data-ttu-id="cf328-181">引发异常，只是为了处理真正异常的情况，不能处理可预测的事件或流控制。</span><span class="sxs-lookup"><span data-stu-id="cf328-181">Throw exceptions only to handle truly extraordinary conditions, not to handle predictable events or flow control.</span></span> <span data-ttu-id="cf328-182">例如，在某些情况下，例如当正在开发类库，是合理的方法参数是无效的因为需要你使用有效的参数来调用的方法引发异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-182">For example, in some cases, such as when you're developing a class library, it's reasonable to throw an exception if a method argument is invalid, because you expect your method to be called with valid parameters.</span></span> <span data-ttu-id="cf328-183">无效的方法参数，如果它不是使用错误的结果表示，出现了异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-183">An invalid method argument, if it is not the result of a usage error, means that something extraordinary has occurred.</span></span> <span data-ttu-id="cf328-184">相反，如果用户输入无效，因为您可以预期用户偶尔会输入无效的数据确实引发了异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-184">Conversely, do not throw an exception if user input is invalid, because you can expect users to occasionally enter invalid data.</span></span> <span data-ttu-id="cf328-185">相反，提供重试机制，以便用户可以输入有效的输入。</span><span class="sxs-lookup"><span data-stu-id="cf328-185">Instead, provide a retry mechanism so users can enter valid input.</span></span> <span data-ttu-id="cf328-186">也不应使用异常处理使用情况的错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-186">Nor should you use exceptions to handle usage errors.</span></span> <span data-ttu-id="cf328-187">请改用[断言](/visualstudio/debugger/assertions-in-managed-code)以确定并更正用法错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-187">Instead, use [assertions](/visualstudio/debugger/assertions-in-managed-code) to identify and correct usage errors.</span></span>  
  
 <span data-ttu-id="cf328-188">此外，不会引发异常时返回代码是不够的;没有转换为异常，则返回代码并不定期执行 catch 异常、 忽略它，并再继续进行处理。</span><span class="sxs-lookup"><span data-stu-id="cf328-188">In addition, do not throw an exception when a return code is sufficient; do not convert a return code to an exception; and do not routinely catch an exception, ignore it, and then continue processing.</span></span>  
  
<a name="Rethrow"></a>   
## <a name="re-throwing-an-exception"></a><span data-ttu-id="cf328-189">重新引发异常</span><span class="sxs-lookup"><span data-stu-id="cf328-189">Re-throwing an exception</span></span>  
 <span data-ttu-id="cf328-190">在许多情况下，异常处理程序只是想要传递到调用方的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-190">In many cases, an exception handler simply wants to pass the exception on to the caller.</span></span> <span data-ttu-id="cf328-191">这通常发生在：</span><span class="sxs-lookup"><span data-stu-id="cf328-191">This most often occurs in:</span></span>  
  
-   <span data-ttu-id="cf328-192">包装的.NET Framework 类库或其他类库中的方法调用的类库。</span><span class="sxs-lookup"><span data-stu-id="cf328-192">A class library that in turn wraps calls to methods in the .NET Framework class library or other class libraries.</span></span>  
  
-   <span data-ttu-id="cf328-193">应用程序或库遇到严重异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-193">An application or library that encounters a fatal exception.</span></span> <span data-ttu-id="cf328-194">异常处理程序可以记录异常，并随后重新引发异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-194">The exception handler can log the exception and then re-throw the exception.</span></span>  
  
 <span data-ttu-id="cf328-195">若要重新引发异常的建议的方法是只需使用[引发](~/docs/csharp/language-reference/keywords/throw.md)C# 中的语句和[引发](~/docs/visual-basic/language-reference/statements/throw-statement.md)在 Visual Basic 中不包含表达式的语句。</span><span class="sxs-lookup"><span data-stu-id="cf328-195">The recommended way to re-throw an exception is to simply use the [throw](~/docs/csharp/language-reference/keywords/throw.md) statement in C# and the [Throw](~/docs/visual-basic/language-reference/statements/throw-statement.md) statement in Visual Basic without including an expression.</span></span> <span data-ttu-id="cf328-196">这可确保当异常传播到调用方保留所有调用堆栈信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-196">This ensures that all call stack information is preserved when the exception is propagated to the caller.</span></span> <span data-ttu-id="cf328-197">下面的示例阐释了这一点。</span><span class="sxs-lookup"><span data-stu-id="cf328-197">The following example illustrates this.</span></span> <span data-ttu-id="cf328-198">一个字符串扩展方法`FindOccurrences`，包装到一个或多个调用<xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType>而无需提前验证其参数。</span><span class="sxs-lookup"><span data-stu-id="cf328-198">A string extension method, `FindOccurrences`, wraps one or more calls to <xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType> without validating its arguments beforehand.</span></span>  
  
 [!code-csharp[System.Exception.Class#6](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow1.cs#6)]
 [!code-vb[System.Exception.Class#6](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow1.vb#6)]  
  
 <span data-ttu-id="cf328-199">然后，调用方调用`FindOccurrences`两次。</span><span class="sxs-lookup"><span data-stu-id="cf328-199">A caller then calls `FindOccurrences` twice.</span></span> <span data-ttu-id="cf328-200">在第二次调用`FindOccurrences`，调用方传递`null`作为搜索字符串，哪些用例<xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType>方法会引发<xref:System.ArgumentNullException>异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-200">In the second call to `FindOccurrences`, the caller passes a `null` as the search string, which cases the <xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType> method to throw an <xref:System.ArgumentNullException> exception.</span></span> <span data-ttu-id="cf328-201">通过处理此异常`FindOccurrences`方法并传递的回调用方。</span><span class="sxs-lookup"><span data-stu-id="cf328-201">This exception is handled by the `FindOccurrences` method and passed back to the caller.</span></span> <span data-ttu-id="cf328-202">因为 throw 语句使用不包含表达式，该示例输出所示保留调用堆栈。</span><span class="sxs-lookup"><span data-stu-id="cf328-202">Because the throw statement is used with no expression, the output from the example shows that the call stack is preserved.</span></span>  
  
 [!code-csharp[System.Exception.Class#7](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow1.cs#7)]
 [!code-vb[System.Exception.Class#7](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow1.vb#7)]  
  
 <span data-ttu-id="cf328-203">相反，如果通过使用重新引发异常</span><span class="sxs-lookup"><span data-stu-id="cf328-203">In contrast, if the exception is re-thrown by using the</span></span>  
  
```csharp  
throw e  
```  
  
```vb  
Throw e  
```  
  
 <span data-ttu-id="cf328-204">语句中，完整的调用堆栈不会保留，且该示例会生成以下输出：</span><span class="sxs-lookup"><span data-stu-id="cf328-204">statement, the full call stack is not preserved, and the example would generate the following output:</span></span>  
  
```Output  
  
'a' occurs at the following character positions: 4, 7, 15  
  
An exception (ArgumentNullException) occurred.  
Message:  
   Value cannot be null.  
Parameter name: value  
  
Stack Trace:  
      at Library.FindOccurrences(String s, String f)  
   at Example.Main()  
  
```  
  
 <span data-ttu-id="cf328-205">稍微更繁琐的替代方法是引发一个新的异常，并保留在内部异常的原始异常的调用堆栈信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-205">A slightly more cumbersome alternative is to throw a new exception, and to preserve the original exception's call stack information in an inner exception.</span></span> <span data-ttu-id="cf328-206">然后，调用方可以使用新异常的<xref:System.Exception.InnerException%2A>属性来检索堆栈帧和原始异常有关的其他信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-206">The caller can then use the new exception's <xref:System.Exception.InnerException%2A> property to retrieve stack frame and other information about the original exception.</span></span> <span data-ttu-id="cf328-207">在这种情况下，在 throw 语句是：</span><span class="sxs-lookup"><span data-stu-id="cf328-207">In this case, the throw statement is:</span></span>  
  
 [!code-csharp[System.Exception.Class#8](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow3.cs#8)]
 [!code-vb[System.Exception.Class#8](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow3.vb#8)]  
  
 <span data-ttu-id="cf328-208">处理异常的用户代码必须知道<xref:System.Exception.InnerException%2A>属性包含有关原始异常，如下面的异常处理程序所示。</span><span class="sxs-lookup"><span data-stu-id="cf328-208">The user code that handles the exception has to know that the <xref:System.Exception.InnerException%2A> property contains information about the original exception, as the following exception handler illustrates.</span></span>  
  
 [!code-csharp[System.Exception.Class#9](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow3.cs#9)]
 [!code-vb[System.Exception.Class#9](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow3.vb#9)]  
  
<a name="Standard"></a>   
## <a name="choosing-standard-exceptions"></a><span data-ttu-id="cf328-209">选择标准异常</span><span class="sxs-lookup"><span data-stu-id="cf328-209">Choosing standard exceptions</span></span>  
 <span data-ttu-id="cf328-210">如果您不得不引发异常，通常可以使用而不是实现自定义异常在.NET Framework 中的现有异常类型。</span><span class="sxs-lookup"><span data-stu-id="cf328-210">When you have to throw an exception, you can often use an existing exception type in the .NET Framework instead of implementing a custom exception.</span></span> <span data-ttu-id="cf328-211">应使用这两个条件下的标准异常类型：</span><span class="sxs-lookup"><span data-stu-id="cf328-211">You should use a standard exception type under these two conditions:</span></span>  
  
-   <span data-ttu-id="cf328-212">将引发异常导致的用法错误 (即，通过所做的开发人员正在调用您的方法的程序逻辑中的错误)。</span><span class="sxs-lookup"><span data-stu-id="cf328-212">You are throwing an exception that is caused by a usage error (that is, by an error in program logic made by the developer who is calling your method).</span></span> <span data-ttu-id="cf328-213">通常情况下，会如引发异常<xref:System.ArgumentException>， <xref:System.ArgumentNullException>， <xref:System.InvalidOperationException>，或<xref:System.NotSupportedException>。</span><span class="sxs-lookup"><span data-stu-id="cf328-213">Typically, you would throw an exception such as <xref:System.ArgumentException>, <xref:System.ArgumentNullException>, <xref:System.InvalidOperationException>, or <xref:System.NotSupportedException>.</span></span> <span data-ttu-id="cf328-214">该字符串时需要提供对异常对象的构造函数实例化的异常对象应描述该错误，以便开发人员可以修复此错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-214">The string you supply to the exception object's constructor when instantiating the exception object should describe the error so that the developer can fix it.</span></span> <span data-ttu-id="cf328-215">有关更多信息，请参见 <xref:System.Exception.Message%2A> 属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-215">For more information, see the <xref:System.Exception.Message%2A> property.</span></span>  
  
-   <span data-ttu-id="cf328-216">处理错误，可以传送到现有的.NET Framework 异常的调用方。</span><span class="sxs-lookup"><span data-stu-id="cf328-216">You are handling an error that can be communicated to the caller with an existing .NET Framework exception.</span></span> <span data-ttu-id="cf328-217">您应引发派生程度最高的可能异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-217">You should throw the most derived exception possible.</span></span> <span data-ttu-id="cf328-218">例如，如果一种方法需要参数是枚举类型的有效成员，则应引发<xref:System.ComponentModel.InvalidEnumArgumentException>（大多数派生类） 而非<xref:System.ArgumentException>。</span><span class="sxs-lookup"><span data-stu-id="cf328-218">For example, if a method requires an argument to be a valid member of an enumeration type, you should throw an <xref:System.ComponentModel.InvalidEnumArgumentException> (the most derived class) rather than an <xref:System.ArgumentException>.</span></span>  
  
 <span data-ttu-id="cf328-219">下表列出了常见的异常类型和其下会引发它们的条件。</span><span class="sxs-lookup"><span data-stu-id="cf328-219">The following table lists common exception types and the conditions under which you would throw them.</span></span>  
  
|<span data-ttu-id="cf328-220">例外</span><span class="sxs-lookup"><span data-stu-id="cf328-220">Exception</span></span>|<span data-ttu-id="cf328-221">条件</span><span class="sxs-lookup"><span data-stu-id="cf328-221">Condition</span></span>|  
|---------------|---------------|  
|<xref:System.ArgumentException>|<span data-ttu-id="cf328-222">传递给方法的非 null 参数无效。</span><span class="sxs-lookup"><span data-stu-id="cf328-222">A non-null argument that is passed to a method is invalid.</span></span>|  
|<xref:System.ArgumentNullException>|<span data-ttu-id="cf328-223">传递给方法的参数是`null`。</span><span class="sxs-lookup"><span data-stu-id="cf328-223">An argument that is passed to a method is `null`.</span></span>|  
|<xref:System.ArgumentOutOfRangeException>|<span data-ttu-id="cf328-224">参数是有效的值范围之外。</span><span class="sxs-lookup"><span data-stu-id="cf328-224">An argument is outside the range of valid values.</span></span>|  
|<xref:System.IO.DirectoryNotFoundException>|<span data-ttu-id="cf328-225">目录路径的一部分无效。</span><span class="sxs-lookup"><span data-stu-id="cf328-225">Part of a directory path is not valid.</span></span>|  
|<xref:System.DivideByZeroException>|<span data-ttu-id="cf328-226">一个整数中的分母或<xref:System.Decimal>除法运算为零。</span><span class="sxs-lookup"><span data-stu-id="cf328-226">The denominator in an integer or <xref:System.Decimal> division operation is zero.</span></span>|  
|<xref:System.IO.DriveNotFoundException>|<span data-ttu-id="cf328-227">驱动器不可用或不存在。</span><span class="sxs-lookup"><span data-stu-id="cf328-227">A drive is unavailable or does not exist.</span></span>|  
|<xref:System.IO.FileNotFoundException>|<span data-ttu-id="cf328-228">文件不存在。</span><span class="sxs-lookup"><span data-stu-id="cf328-228">A file does not exist.</span></span>|  
|<xref:System.FormatException>|<span data-ttu-id="cf328-229">值不在相应的格式将待换算从字符串转换方法如`Parse`。</span><span class="sxs-lookup"><span data-stu-id="cf328-229">A value is not in an appropriate format to be converted from a string by a conversion method such as `Parse`.</span></span>|  
|<xref:System.IndexOutOfRangeException>|<span data-ttu-id="cf328-230">索引是数组或集合的界限外。</span><span class="sxs-lookup"><span data-stu-id="cf328-230">An index is outside the bounds of an array or collection.</span></span>|  
|<xref:System.InvalidOperationException>|<span data-ttu-id="cf328-231">方法调用对象的当前状态无效。</span><span class="sxs-lookup"><span data-stu-id="cf328-231">A method call is invalid in an object's current state.</span></span>|  
|<xref:System.Collections.Generic.KeyNotFoundException>|<span data-ttu-id="cf328-232">找不到用于访问集合中的成员的指定的键。</span><span class="sxs-lookup"><span data-stu-id="cf328-232">The specified key for accessing a member in a collection cannot be found.</span></span>|  
|<xref:System.NotImplementedException>|<span data-ttu-id="cf328-233">未实现方法或操作。</span><span class="sxs-lookup"><span data-stu-id="cf328-233">A method or operation is not implemented.</span></span>|  
|<xref:System.NotSupportedException>|<span data-ttu-id="cf328-234">不支持方法或操作。</span><span class="sxs-lookup"><span data-stu-id="cf328-234">A method or operation is not supported.</span></span>|  
|<xref:System.ObjectDisposedException>|<span data-ttu-id="cf328-235">已释放的对象上执行的操作。</span><span class="sxs-lookup"><span data-stu-id="cf328-235">An operation is performed on an object that has been disposed.</span></span>|  
|<xref:System.OverflowException>|<span data-ttu-id="cf328-236">当算术、 强制转换或转换操作会导致溢出。</span><span class="sxs-lookup"><span data-stu-id="cf328-236">An arithmetic, casting, or conversion operation results in an overflow.</span></span>|  
|<xref:System.IO.PathTooLongException>|<span data-ttu-id="cf328-237">路径或文件名称超出了系统定义的最大长度。</span><span class="sxs-lookup"><span data-stu-id="cf328-237">A path or file name exceeds the maximum system-defined length.</span></span>|  
|<xref:System.PlatformNotSupportedException>|<span data-ttu-id="cf328-238">在当前平台上不支持该操作。</span><span class="sxs-lookup"><span data-stu-id="cf328-238">The operation is not supported on the current platform.</span></span>|  
|<xref:System.RankException>|<span data-ttu-id="cf328-239">具有错误维数的数组传递给方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-239">An array with the wrong number of dimensions is passed to a method.</span></span>|  
|<xref:System.TimeoutException>|<span data-ttu-id="cf328-240">分配给操作的时间间隔已过期。</span><span class="sxs-lookup"><span data-stu-id="cf328-240">The time interval allotted to an operation has expired.</span></span>|  
|<xref:System.UriFormatException>|<span data-ttu-id="cf328-241">使用无效的统一资源标识符 (URI)。</span><span class="sxs-lookup"><span data-stu-id="cf328-241">An invalid Uniform Resource Identifier (URI) is used.</span></span>|  
  
<a name="Custom"></a>   
## <a name="implementing-custom-exceptions"></a><span data-ttu-id="cf328-242">实现自定义异常</span><span class="sxs-lookup"><span data-stu-id="cf328-242">Implementing custom exceptions</span></span>  
 <span data-ttu-id="cf328-243">在以下情况下，使用现有的.NET Framework 异常处理的错误条件不能满足：</span><span class="sxs-lookup"><span data-stu-id="cf328-243">In the following cases, using an existing .NET Framework exception to handle an error condition is not adequate:</span></span>  
  
-   <span data-ttu-id="cf328-244">当异常反映了无法映射到现有的.NET Framework 异常的唯一程序错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-244">When the exception reflects a unique program error that cannot be mapped to an existing .NET Framework exception.</span></span>  
  
-   <span data-ttu-id="cf328-245">异常时需要处理的是不同于适用于现有的.NET Framework 异常或异常的处理必须从类似的异常消除歧义。</span><span class="sxs-lookup"><span data-stu-id="cf328-245">When the exception requires handling that is different from the handling that is appropriate for an existing .NET Framework exception, or the exception must be disambiguated from a similar exception.</span></span> <span data-ttu-id="cf328-246">例如，如果引发<xref:System.ArgumentOutOfRangeException>异常分析不在目标整型类型的范围内的字符串的数值表示形式时，您不想要使用相同的异常错误的结果从调用方未提供相应约束的值时调用的方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-246">For example, if you throw an <xref:System.ArgumentOutOfRangeException> exception when parsing the numeric representation of a string that is out of range of the target integral type, you would not want to use the same exception for an error that results from the caller not supplying the appropriate constrained values when calling the method.</span></span>  
  
 <span data-ttu-id="cf328-247"><xref:System.Exception>类是.NET Framework 中的所有异常的基类。</span><span class="sxs-lookup"><span data-stu-id="cf328-247">The <xref:System.Exception> class is the base class of all exceptions in the .NET Framework.</span></span> <span data-ttu-id="cf328-248">多个派生的类要依赖于的成员的继承行为<xref:System.Exception>类; 它们不会重写的成员<xref:System.Exception>，也不定义任何唯一成员。</span><span class="sxs-lookup"><span data-stu-id="cf328-248">Many derived classes rely on the inherited behavior of the members of the <xref:System.Exception> class; they do not override the members of <xref:System.Exception>, nor do they define any unique members.</span></span>  
  
 <span data-ttu-id="cf328-249">若要定义自己的异常类：</span><span class="sxs-lookup"><span data-stu-id="cf328-249">To define your own exception class:</span></span>  
  
1.  <span data-ttu-id="cf328-250">定义一个类，继承自<xref:System.Exception>。</span><span class="sxs-lookup"><span data-stu-id="cf328-250">Define a class that inherits from <xref:System.Exception>.</span></span> <span data-ttu-id="cf328-251">如果有必要，请定义您的类提供有关异常的其他信息所需的任何唯一成员。</span><span class="sxs-lookup"><span data-stu-id="cf328-251">If necessary, define any unique members needed by your class to provide additional information about the exception.</span></span> <span data-ttu-id="cf328-252">例如，<xref:System.ArgumentException>类包括<xref:System.ArgumentException.ParamName%2A>属性，它指定其参数导致异常的参数的名称和<xref:System.Text.RegularExpressions.RegexMatchTimeoutException>属性包含<xref:System.Text.RegularExpressions.RegexMatchTimeoutException.MatchTimeout%2A>属性，指示在超时间隔。</span><span class="sxs-lookup"><span data-stu-id="cf328-252">For example, the <xref:System.ArgumentException> class includes a <xref:System.ArgumentException.ParamName%2A> property that specifies the name of the parameter whose argument caused the exception, and the <xref:System.Text.RegularExpressions.RegexMatchTimeoutException> property includes a <xref:System.Text.RegularExpressions.RegexMatchTimeoutException.MatchTimeout%2A> property that indicates the time-out interval.</span></span>  
  
2.  <span data-ttu-id="cf328-253">如有必要，重写任何继承的成员你想要更改或修改它的功能。</span><span class="sxs-lookup"><span data-stu-id="cf328-253">If necessary, override any inherited members whose functionality you want to change or modify.</span></span> <span data-ttu-id="cf328-254">请注意，大多数现有派生类的<xref:System.Exception>不会重写继承成员的行为。</span><span class="sxs-lookup"><span data-stu-id="cf328-254">Note that most existing derived classes of <xref:System.Exception> do not override the behavior of inherited members.</span></span>  
  
3.  <span data-ttu-id="cf328-255">确定您的自定义异常对象是可序列化。</span><span class="sxs-lookup"><span data-stu-id="cf328-255">Determine whether your custom exception object is serializable.</span></span> <span data-ttu-id="cf328-256">序列化使您可以保存有关异常的信息，并允许异常信息在由服务器和客户端代理在远程处理的上下文中共享。</span><span class="sxs-lookup"><span data-stu-id="cf328-256">Serialization enables you to save information about the exception and permits exception information to be shared by a server and a client proxy in a remoting context.</span></span> <span data-ttu-id="cf328-257">若要使异常对象可序列化，将其与标记<xref:System.SerializableAttribute>属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-257">To make the exception object serializable, mark it with the <xref:System.SerializableAttribute> attribute.</span></span>  
  
4.  <span data-ttu-id="cf328-258">定义异常类的构造函数。</span><span class="sxs-lookup"><span data-stu-id="cf328-258">Define the constructors of your exception class.</span></span> <span data-ttu-id="cf328-259">通常情况下，异常类都有一个或多个以下构造函数：</span><span class="sxs-lookup"><span data-stu-id="cf328-259">Typically, exception classes have one or more of the following constructors:</span></span>  
  
    -   <span data-ttu-id="cf328-260"><xref:System.Exception.%23ctor>它使用默认值初始化新的异常对象的属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-260"><xref:System.Exception.%23ctor>, which uses default values to initialize the properties of a new exception object.</span></span>  
  
    -   <span data-ttu-id="cf328-261"><xref:System.Exception.%23ctor%28System.String%29>其中初始化具有指定的错误消息的新异常对象。</span><span class="sxs-lookup"><span data-stu-id="cf328-261"><xref:System.Exception.%23ctor%28System.String%29>, which initializes a new exception object with a specified error message.</span></span>  
  
    -   <span data-ttu-id="cf328-262"><xref:System.Exception.%23ctor%28System.String%2CSystem.Exception%29>其中初始化使用指定的错误消息和内部异常的新异常对象。</span><span class="sxs-lookup"><span data-stu-id="cf328-262"><xref:System.Exception.%23ctor%28System.String%2CSystem.Exception%29>, which initializes a new exception object with a specified error message and inner exception.</span></span>  
  
    -   <span data-ttu-id="cf328-263"><xref:System.Exception.%23ctor%28System.Runtime.Serialization.SerializationInfo%2CSystem.Runtime.Serialization.StreamingContext%29>它是`protected`初始化中的新异常对象的构造函数序列化数据。</span><span class="sxs-lookup"><span data-stu-id="cf328-263"><xref:System.Exception.%23ctor%28System.Runtime.Serialization.SerializationInfo%2CSystem.Runtime.Serialization.StreamingContext%29>, which is a `protected` constructor that initializes a new exception object from serialized data.</span></span> <span data-ttu-id="cf328-264">如果已选择使异常对象可序列化，则应实现此构造函数。</span><span class="sxs-lookup"><span data-stu-id="cf328-264">You should implement this constructor if you've chosen to make your exception object serializable.</span></span>  
  
 <span data-ttu-id="cf328-265">下面的示例演示如何使用自定义异常类。</span><span class="sxs-lookup"><span data-stu-id="cf328-265">The following example illustrates the use of a custom exception class.</span></span> <span data-ttu-id="cf328-266">它定义`NotPrimeException`客户端尝试通过指定一个起始数字，不是质数的话检索一系列质数时引发的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-266">It defines a `NotPrimeException` exception that is thrown when a client tries to retrieve a sequence of prime numbers by specifying a starting number that is not prime.</span></span> <span data-ttu-id="cf328-267">异常定义新的属性， `NonPrime`，返回非的-质数，导致了异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-267">The exception defines a new property, `NonPrime`, that returns the non-prime number that caused the exception.</span></span> <span data-ttu-id="cf328-268">除了实现受保护的无参数构造函数和一个构造函数与<xref:System.Runtime.Serialization.SerializationInfo>并<xref:System.Runtime.Serialization.StreamingContext>序列化的参数`NotPrimeException`类定义了三个额外的构造函数，以支持`NonPrime`属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-268">Besides implementing a protected parameterless constructor and a constructor with <xref:System.Runtime.Serialization.SerializationInfo> and <xref:System.Runtime.Serialization.StreamingContext> parameters for serialization, the `NotPrimeException` class defines three additional constructors to support the `NonPrime` property.</span></span>  <span data-ttu-id="cf328-269">每个构造函数调用基类构造函数除了保留值的非-质数。</span><span class="sxs-lookup"><span data-stu-id="cf328-269">Each constructor calls a base class constructor in addition to preserving the value of the non-prime number.</span></span> <span data-ttu-id="cf328-270">`NotPrimeException`类还带有<xref:System.SerializableAttribute>属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-270">The `NotPrimeException` class is also marked with the <xref:System.SerializableAttribute> attribute.</span></span>  
  
 [!code-csharp[System.Exception.Class#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/notprimeexception.cs#1)]
 [!code-vb[System.Exception.Class#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/notprimeexception.vb#1)]  
  
 <span data-ttu-id="cf328-271">`PrimeNumberGenerator`类在下面的示例所示使用埃拉托色的埃拉托色尼斯来计算的一系列质数从 2 到客户端对其类构造函数的调用中指定的限制。</span><span class="sxs-lookup"><span data-stu-id="cf328-271">The `PrimeNumberGenerator` class shown in the following example uses the Sieve of Eratosthenes to calculate the sequence of prime numbers from 2 to a limit specified by the client in the call to its class constructor.</span></span> <span data-ttu-id="cf328-272">`GetPrimesFrom`方法返回大于或等于指定的下限值的所有质数，但会引发`NotPrimeException`如果该较低的限制不是一个素数。</span><span class="sxs-lookup"><span data-stu-id="cf328-272">The `GetPrimesFrom` method returns all prime numbers that are greater than or equal to a specified lower limit, but throws a `NotPrimeException` if that lower limit is not a prime number.</span></span>  
  
 [!code-csharp[System.Exception.Class#2](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/primenumbergenerator.cs#2)]
 [!code-vb[System.Exception.Class#2](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/primenumbergenerator.vb#2)]  
  
 <span data-ttu-id="cf328-273">下面的示例调用两`GetPrimesFrom`方法与非质数，其中之一是跨应用程序域边界。</span><span class="sxs-lookup"><span data-stu-id="cf328-273">The following example makes two calls to the `GetPrimesFrom` method with non-prime numbers, one of which crosses application domain boundaries.</span></span> <span data-ttu-id="cf328-274">在这两种情况下，引发了异常并已成功处理客户端代码中。</span><span class="sxs-lookup"><span data-stu-id="cf328-274">In both cases, the exception is thrown and successfully handled in client code.</span></span>  
  
 [!code-csharp[System.Exception.Class#3](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/example.cs#3)]
 [!code-vb[System.Exception.Class#3](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/example.vb#3)]  
  
## <a name="windows-runtime-and-includenetv451includesnet-v451-mdmd"></a><span data-ttu-id="cf328-275">Windows 运行时和 [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span><span class="sxs-lookup"><span data-stu-id="cf328-275">Windows Runtime and [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span></span>  
 <span data-ttu-id="cf328-276">在中[!INCLUDE[net_win8_profile](~/includes/net-win8-profile-md.md)]为[!INCLUDE[win8](~/includes/win8-md.md)]，通过.NET Framework 堆栈帧传播异常时会通常丢失一些异常的信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-276">In [!INCLUDE[net_win8_profile](~/includes/net-win8-profile-md.md)] for [!INCLUDE[win8](~/includes/win8-md.md)], some exception information is typically lost when an exception is propagated through non-.NET Framework stack frames.</span></span> <span data-ttu-id="cf328-277">从开始[!INCLUDE[net_v451](~/includes/net-v451-md.md)]并[!INCLUDE[win81](~/includes/win81-md.md)]，公共语言运行时仍会继续使用原始<xref:System.Exception>除非已在.NET Framework 堆栈帧中修改该异常引发的对象。</span><span class="sxs-lookup"><span data-stu-id="cf328-277">Starting with the [!INCLUDE[net_v451](~/includes/net-v451-md.md)] and [!INCLUDE[win81](~/includes/win81-md.md)], the common language runtime continues to use the original <xref:System.Exception> object that was thrown unless that exception was modified in a non-.NET Framework stack frame.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-278">下面的示例演示`catch`块定义为处理<xref:System.ArithmeticException>错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-278">The following example demonstrates a `catch` block that is defined to handle <xref:System.ArithmeticException> errors.</span></span> <span data-ttu-id="cf328-279">这`catch`块还捕捉<xref:System.DivideByZeroException>错误，因为<xref:System.DivideByZeroException>派生自<xref:System.ArithmeticException>，并且没有任何`catch`显式定义为块<xref:System.DivideByZeroException>错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-279">This `catch` block also catches <xref:System.DivideByZeroException> errors, because <xref:System.DivideByZeroException> derives from <xref:System.ArithmeticException> and there is no `catch` block explicitly defined for <xref:System.DivideByZeroException> errors.</span></span>  
  
 [!code-cpp[CatchException#1](~/samples/snippets/cpp/VS_Snippets_CLR/CatchException/CPP/catchexception.cpp#1)]
 [!code-csharp[CatchException#1](~/samples/snippets/csharp/VS_Snippets_CLR/CatchException/CS/catchexception.cs#1)]
 [!code-vb[CatchException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/CatchException/VB/catchexception.vb#1)]  
  
 ]]></format>
    </remarks>
    <related type="Article" href="~/docs/standard/exceptions/index.md"><span data-ttu-id="cf328-280">处理和引发异常</span><span class="sxs-lookup"><span data-stu-id="cf328-280">Handling and Throwing Exceptions</span></span></related>
    <related type="Article" href="~/docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md"><span data-ttu-id="cf328-281">打包和部署桌面应用程序中的资源</span><span class="sxs-lookup"><span data-stu-id="cf328-281">Packaging and Deploying Resources in Desktop Apps</span></span></related>
    <related type="Article" href="https://msdn.microsoft.com/library/70ab2522-6486-4076-a1a9-e0f11cd0f3a1"><span data-ttu-id="cf328-282">托管代码中的断言</span><span class="sxs-lookup"><span data-stu-id="cf328-282">Assertions in Managed Code</span></span></related>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="cf328-283">初始化 <see cref="T:System.Exception" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="cf328-283">Initializes a new instance of the <see cref="T:System.Exception" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public Exception ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; Exception();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="cf328-284">初始化 <see cref="T:System.Exception" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="cf328-284">Initializes a new instance of the <see cref="T:System.Exception" /> class.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-285">此构造函数将新实例的 <xref:System.Exception.Message%2A> 属性初始化为系统提供的消息，该消息描述错误并考虑当前系统区域性。</span><span class="sxs-lookup"><span data-stu-id="cf328-285">This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="cf328-286">所有派生的类应提供此默认构造函数。</span><span class="sxs-lookup"><span data-stu-id="cf328-286">All the derived classes should provide this default constructor.</span></span> <span data-ttu-id="cf328-287">下表显示 <xref:System.Exception> 的实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="cf328-287">The following table shows the initial property values for an instance of <xref:System.Exception>.</span></span>  
  
|<span data-ttu-id="cf328-288">Property</span><span class="sxs-lookup"><span data-stu-id="cf328-288">Property</span></span>|<span data-ttu-id="cf328-289">“值”</span><span class="sxs-lookup"><span data-stu-id="cf328-289">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="cf328-290">空引用（在 Visual Basic 中为 `Nothing`）。</span><span class="sxs-lookup"><span data-stu-id="cf328-290">A null reference (`Nothing` in Visual Basic).</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="cf328-291">系统提供的本地化说明。</span><span class="sxs-lookup"><span data-stu-id="cf328-291">A system-supplied localized description.</span></span>|  
  
   
  
## Examples  
 <span data-ttu-id="cf328-292">以下代码示例从`Exception`，它使用预定义的消息。</span><span class="sxs-lookup"><span data-stu-id="cf328-292">The following code example derives an `Exception` that uses a predefined message.</span></span> <span data-ttu-id="cf328-293">该代码演示如何使用无参数构造函数派生的类和基`Exception`类。</span><span class="sxs-lookup"><span data-stu-id="cf328-293">The code demonstrates the use of the parameterless constructor for the derived class and the base `Exception` class.</span></span>  
  
 [!code-cpp[System.Exception.Ctor#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Ctor/CPP/new.cpp#1)]
 [!code-csharp[System.Exception.Ctor#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Ctor/CS/new.cs#1)]
 [!code-vb[System.Exception.Ctor#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Ctor/VB/new.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public Exception (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; Exception(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new Exception : string -&gt; Exception" Usage="new System.Exception message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="cf328-294">描述错误的消息。</span><span class="sxs-lookup"><span data-stu-id="cf328-294">The message that describes the error.</span></span></param>
        <summary><span data-ttu-id="cf328-295">用指定的错误消息初始化 <see cref="T:System.Exception" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="cf328-295">Initializes a new instance of the <see cref="T:System.Exception" /> class with a specified error message.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-296">此构造函数初始化<xref:System.Exception.Message%2A>属性使用的新实例的`message`参数。</span><span class="sxs-lookup"><span data-stu-id="cf328-296">This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance by using the `message` parameter.</span></span> <span data-ttu-id="cf328-297">如果`message`参数是`null`，这是调用相同<xref:System.Exception.%23ctor%2A>构造函数。</span><span class="sxs-lookup"><span data-stu-id="cf328-297">If the `message` parameter is `null`, this is the same as calling the <xref:System.Exception.%23ctor%2A> constructor.</span></span>  
  
 <span data-ttu-id="cf328-298">下表显示 <xref:System.Exception> 的实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="cf328-298">The following table shows the initial property values for an instance of <xref:System.Exception>.</span></span>  
  
|<span data-ttu-id="cf328-299">Property</span><span class="sxs-lookup"><span data-stu-id="cf328-299">Property</span></span>|<span data-ttu-id="cf328-300">“值”</span><span class="sxs-lookup"><span data-stu-id="cf328-300">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="cf328-301">空引用（在 Visual Basic 中为 `Nothing`）。</span><span class="sxs-lookup"><span data-stu-id="cf328-301">A null reference (`Nothing` in Visual Basic).</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="cf328-302">错误消息字符串。</span><span class="sxs-lookup"><span data-stu-id="cf328-302">The error message string.</span></span>|  
  
   
  
## Examples  
 <span data-ttu-id="cf328-303">以下代码示例从`Exception`的特定条件。</span><span class="sxs-lookup"><span data-stu-id="cf328-303">The following code example derives an `Exception` for a specific condition.</span></span> <span data-ttu-id="cf328-304">该代码演示如何调用指定的消息将作为参数，用于派生的类和基类的构造函数使用`Exception`类。</span><span class="sxs-lookup"><span data-stu-id="cf328-304">The code demonstrates the use of the constructor that takes a caller-specified message as a parameter, for both the derived class and the base `Exception` class.</span></span>  
  
 [!code-cpp[System.Exception.Ctor#2](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Ctor/CPP/news.cpp#2)]
 [!code-csharp[System.Exception.Ctor#2](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Ctor/CS/news.cs#2)]
 [!code-vb[System.Exception.Ctor#2](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Ctor/VB/news.vb#2)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected Exception (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; Exception(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new Exception : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; Exception" Usage="new System.Exception (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
          <AttributeName>System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="cf328-305">包含有关所引发异常的序列化对象数据的 <see cref="T:System.Runtime.Serialization.SerializationInfo" />。</span><span class="sxs-lookup"><span data-stu-id="cf328-305">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</span></span></param>
        <param name="context"><span data-ttu-id="cf328-306"><see cref="T:System.Runtime.Serialization.StreamingContext" />，它包含关于源或目标的上下文信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-306">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="cf328-307">用序列化数据初始化 <see cref="T:System.Exception" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="cf328-307">Initializes a new instance of the <see cref="T:System.Exception" /> class with serialized data.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-308">此构造函数在反序列化过程中调用，以便重建通过流传输的异常对象。</span><span class="sxs-lookup"><span data-stu-id="cf328-308">This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</span></span> <span data-ttu-id="cf328-309">有关详细信息，请参阅[XML 和 SOAP 序列化](~/docs/standard/serialization/xml-and-soap-serialization.md)。</span><span class="sxs-lookup"><span data-stu-id="cf328-309">For more information, see [XML and SOAP Serialization](~/docs/standard/serialization/xml-and-soap-serialization.md).</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-310">下面的代码示例定义一个派生可序列化`Exception`类。</span><span class="sxs-lookup"><span data-stu-id="cf328-310">The following code example defines a derived serializable `Exception` class.</span></span> <span data-ttu-id="cf328-311">代码强制被零除错误，然后创建派生的异常使用的实例 (<xref:System.Runtime.Serialization.SerializationInfo>， <xref:System.Runtime.Serialization.StreamingContext>) 构造函数。</span><span class="sxs-lookup"><span data-stu-id="cf328-311">The code forces a divide-by-0 error and then creates an instance of the derived exception using the (<xref:System.Runtime.Serialization.SerializationInfo>, <xref:System.Runtime.Serialization.StreamingContext>) constructor.</span></span> <span data-ttu-id="cf328-312">代码序列化到文件的实例，则反文件序列化为一个新的异常，则会引发，然后捕获并显示异常的数据。</span><span class="sxs-lookup"><span data-stu-id="cf328-312">The code serializes the instance to a file, deserializes the file into a new exception, which it throws, and then catches and displays the exception's data.</span></span>  
  
 [!code-cpp[System.Exception.GetObjectData#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CPP/getobjdata.cpp#1)]
 [!code-csharp[System.Exception.GetObjectData#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CS/getobjdata.cs#1)]
 [!code-vb[System.Exception.GetObjectData#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.GetObjectData/VB/getobjdata.vb#1)]  
  
 ]]></format>
        </remarks>
        <exception cref="T:System.ArgumentNullException"><span data-ttu-id="cf328-313"><paramref name="info" /> 参数为 <see langword="null" />。</span><span class="sxs-lookup"><span data-stu-id="cf328-313">The <paramref name="info" /> parameter is <see langword="null" />.</span></span></exception>
        <exception cref="T:System.Runtime.Serialization.SerializationException"><span data-ttu-id="cf328-314">类名为 <see langword="null" /> 或者 <see cref="P:System.Exception.HResult" /> 为零 (0)。</span><span class="sxs-lookup"><span data-stu-id="cf328-314">The class name is <see langword="null" /> or <see cref="P:System.Exception.HResult" /> is zero (0).</span></span></exception>
        <altmember cref="T:System.Runtime.Serialization.SerializationInfo" />
        <altmember cref="T:System.Runtime.Serialization.StreamingContext" />
        <related type="Article" href="~/docs/standard/serialization/xml-and-soap-serialization.md"><span data-ttu-id="cf328-315">XML 和 SOAP 序列化</span><span class="sxs-lookup"><span data-stu-id="cf328-315">XML and SOAP Serialization</span></span></related>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public Exception (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; Exception(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new Exception : string * Exception -&gt; Exception" Usage="new System.Exception (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="cf328-316">解释异常原因的错误消息。</span><span class="sxs-lookup"><span data-stu-id="cf328-316">The error message that explains the reason for the exception.</span></span></param>
        <param name="innerException"><span data-ttu-id="cf328-317">导致当前异常的异常；如果未指定内部异常，则是一个 null 引用（在 Visual Basic 中为 <see langword="Nothing" />）。</span><span class="sxs-lookup"><span data-stu-id="cf328-317">The exception that is the cause of the current exception, or a null reference (<see langword="Nothing" /> in Visual Basic) if no inner exception is specified.</span></span></param>
        <summary><span data-ttu-id="cf328-318">使用指定的错误消息和对作为此异常原因的内部异常的引用来初始化 <see cref="T:System.Exception" /> 类的新实例。</span><span class="sxs-lookup"><span data-stu-id="cf328-318">Initializes a new instance of the <see cref="T:System.Exception" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-319">因前一个异常而直接引发的异常应在 <xref:System.Exception.InnerException%2A> 属性中包含对前一个异常的引用。</span><span class="sxs-lookup"><span data-stu-id="cf328-319">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="cf328-320"><xref:System.Exception.InnerException%2A> 属性返回传递到构造函数中的相同值，或者如果 `Nothing` 属性不向构造函数提供内部异常值，则为空引用（在 Visual Basic 中为 <xref:System.Exception.InnerException%2A>）。</span><span class="sxs-lookup"><span data-stu-id="cf328-320">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="cf328-321">下表显示 <xref:System.Exception> 的实例的初始属性值。</span><span class="sxs-lookup"><span data-stu-id="cf328-321">The following table shows the initial property values for an instance of <xref:System.Exception>.</span></span>  
  
|<span data-ttu-id="cf328-322">Property</span><span class="sxs-lookup"><span data-stu-id="cf328-322">Property</span></span>|<span data-ttu-id="cf328-323">“值”</span><span class="sxs-lookup"><span data-stu-id="cf328-323">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="cf328-324">内部异常引用。</span><span class="sxs-lookup"><span data-stu-id="cf328-324">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="cf328-325">错误消息字符串。</span><span class="sxs-lookup"><span data-stu-id="cf328-325">The error message string.</span></span>|  
  
   
  
## Examples  
 <span data-ttu-id="cf328-326">以下代码示例从`Exception`的特定条件。</span><span class="sxs-lookup"><span data-stu-id="cf328-326">The following code example derives an `Exception` for a specific condition.</span></span> <span data-ttu-id="cf328-327">该代码演示如何采用消息和内部异常作为参数，分别对应派生的类和基类的构造函数使用`Exception`类。</span><span class="sxs-lookup"><span data-stu-id="cf328-327">The code demonstrates the use of the constructor that takes a message and an inner exception as parameters, for both the derived class and the base `Exception` class.</span></span>  
  
 [!code-cpp[System.Exception.Ctor#3](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Ctor/CPP/newsi.cpp#3)]
 [!code-csharp[System.Exception.Ctor#3](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Ctor/CS/newsi.cs#3)]
 [!code-vb[System.Exception.Ctor#3](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Ctor/VB/newsi.vb#3)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Data">
      <MemberSignature Language="C#" Value="public virtual System.Collections.IDictionary Data { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Collections.IDictionary Data" />
      <MemberSignature Language="DocId" Value="P:System.Exception.Data" />
      <MemberSignature Language="VB.NET" Value="Public Overridable ReadOnly Property Data As IDictionary" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::Collections::IDictionary ^ Data { System::Collections::IDictionary ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Data : System.Collections.IDictionary" Usage="System.Exception.Data" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netstandard-1.0;netstandard-1.1;netstandard-1.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
          <AttributeName>get: System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Collections.IDictionary</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-328">获取提供有关异常的其他用户定义信息的键/值对集合。</span><span class="sxs-lookup"><span data-stu-id="cf328-328">Gets a collection of key/value pairs that provide additional user-defined information about the exception.</span></span></summary>
        <value><span data-ttu-id="cf328-329">一个对象，它实现 <see cref="T:System.Collections.IDictionary" /> 接口并包含用户定义的键/值对的集合。</span><span class="sxs-lookup"><span data-stu-id="cf328-329">An object that implements the <see cref="T:System.Collections.IDictionary" /> interface and contains a collection of user-defined key/value pairs.</span></span> <span data-ttu-id="cf328-330">默认值为空集合。</span><span class="sxs-lookup"><span data-stu-id="cf328-330">The default is an empty collection.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-331">使用<xref:System.Collections.IDictionary?displayProperty=nameWithType>返回对象<xref:System.Exception.Data%2A>属性来存储和检索与异常相关的补充信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-331">Use the <xref:System.Collections.IDictionary?displayProperty=nameWithType> object returned by the <xref:System.Exception.Data%2A> property to store and retrieve supplementary information relevant to the exception.</span></span> <span data-ttu-id="cf328-332">信息是在任意数量的用户定义键/值对的形式。</span><span class="sxs-lookup"><span data-stu-id="cf328-332">The information is in the form of an arbitrary number of user-defined key/value pairs.</span></span> <span data-ttu-id="cf328-333">每个键/值对的关键组件通常是对象的一个标识字符串，而该对的值组件可以是对象的任何类型。</span><span class="sxs-lookup"><span data-stu-id="cf328-333">The key component of each key/value pair is typically an identifying string, whereas the value component of the pair can be any type of object.</span></span>  
  
## <a name="keyvalue-pair-security"></a><span data-ttu-id="cf328-334">键/值对安全</span><span class="sxs-lookup"><span data-stu-id="cf328-334">Key/Value Pair Security</span></span>  
 <span data-ttu-id="cf328-335">返回的集合中存储的键/值对<xref:System.Exception.Data%2A>是不安全的属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-335">The key/value pairs stored in the collection returned by the <xref:System.Exception.Data%2A> property are not secure.</span></span> <span data-ttu-id="cf328-336">如果你的应用程序调用一系列嵌套的例程，并且每个例程包含异常处理程序时，调用堆栈结果将包含这些异常处理程序的层次结构。</span><span class="sxs-lookup"><span data-stu-id="cf328-336">If your application calls a nested series of routines, and each routine contains exception handlers, the resulting call stack contains a hierarchy of those exception handlers.</span></span> <span data-ttu-id="cf328-337">如果较低级别例程引发了异常，调用堆栈层次结构中的任何高级别的异常处理程序可以读取和/或修改存储在集合中的任何其他异常处理程序的键/值对。</span><span class="sxs-lookup"><span data-stu-id="cf328-337">If a lower-level routine throws an exception, any upper-level exception handler in the call stack hierarchy can read and/or modify the key/value pairs stored in the collection by any other exception handler.</span></span> <span data-ttu-id="cf328-338">这意味着您必须保证键/值对中的信息不是机密和你的应用程序将操作正确，如果键/值对中的信息已损坏。</span><span class="sxs-lookup"><span data-stu-id="cf328-338">This means you must guarantee that the information in the key/value pairs is not confidential and that your application will operate correctly if the information in the key/value pairs is corrupted.</span></span>  
  
## <a name="key-conflicts"></a><span data-ttu-id="cf328-339">密钥冲突</span><span class="sxs-lookup"><span data-stu-id="cf328-339">Key Conflicts</span></span>  
 <span data-ttu-id="cf328-340">键冲突发生时不同的异常处理程序指定相同的密钥来访问键/值对。</span><span class="sxs-lookup"><span data-stu-id="cf328-340">A key conflict occurs when different exception handlers specify the same key to access a key/value pair.</span></span> <span data-ttu-id="cf328-341">开发应用程序，因为键冲突的结果是较低级别的异常处理程序会无意中能够更高级别的异常处理程序，与和此通信可能会导致难以察觉的程序错误时要格外小心。</span><span class="sxs-lookup"><span data-stu-id="cf328-341">Use caution when developing your application because the consequence of a key conflict is that lower-level exception handlers can inadvertently communicate with higher-level exception handlers, and this communication might cause subtle program errors.</span></span> <span data-ttu-id="cf328-342">但是，如果您不小心您可以使用键冲突可增强应用程序。</span><span class="sxs-lookup"><span data-stu-id="cf328-342">However, if you are cautious you can use key conflicts to enhance your application.</span></span>  
  
## <a name="avoiding-key-conflicts"></a><span data-ttu-id="cf328-343">避免键冲突</span><span class="sxs-lookup"><span data-stu-id="cf328-343">Avoiding Key Conflicts</span></span>  
 <span data-ttu-id="cf328-344">通过采用命名约定生成的键/值对唯一键可以避免键冲突。</span><span class="sxs-lookup"><span data-stu-id="cf328-344">Avoid key conflicts by adopting a naming convention to generate unique keys for key/value pairs.</span></span> <span data-ttu-id="cf328-345">例如，命名约定可能会生成包含句点分隔的应用程序名称的密钥，它提供对和唯一标识符的补充信息的方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-345">For example, a naming convention might yield a key that consists of the period-delimited name of your application, the method that provides supplementary information for the pair, and a unique identifier.</span></span>  
  
 <span data-ttu-id="cf328-346">假设两个应用程序，名为产品和供应商，每个有一个名为 Sales 方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-346">Suppose two applications, named Products and Suppliers, each has a method named Sales.</span></span> <span data-ttu-id="cf328-347">产品应用程序中的销售方法提供的产品标识号 （单品单元或 SKU）。</span><span class="sxs-lookup"><span data-stu-id="cf328-347">The Sales method in the Products application provides the identification number (the stock keeping unit or SKU) of a product.</span></span> <span data-ttu-id="cf328-348">供应商应用程序中的销售方法提供的标识号或 SID 的供应商。</span><span class="sxs-lookup"><span data-stu-id="cf328-348">The Sales method in the Suppliers application provides the identification number, or SID, of a supplier.</span></span> <span data-ttu-id="cf328-349">因此，此示例中的命名约定将生成密钥，"Products.Sales.SKU"和"Suppliers.Sales.SID"。</span><span class="sxs-lookup"><span data-stu-id="cf328-349">Consequently, the naming convention for this example yields the keys, "Products.Sales.SKU" and "Suppliers.Sales.SID".</span></span>  
  
## <a name="exploiting-key-conflicts"></a><span data-ttu-id="cf328-350">利用键冲突</span><span class="sxs-lookup"><span data-stu-id="cf328-350">Exploiting Key Conflicts</span></span>  
 <span data-ttu-id="cf328-351">通过使用一个或多个特殊的、 预先安排的键存在来控制处理攻击键冲突。</span><span class="sxs-lookup"><span data-stu-id="cf328-351">Exploit key conflicts by using the presence of one or more special, prearranged keys to control processing.</span></span> <span data-ttu-id="cf328-352">假设在一个方案中，调用堆栈层次结构中的最高级别的异常处理程序捕获所有异常引发的较低级别的异常处理程序。</span><span class="sxs-lookup"><span data-stu-id="cf328-352">Suppose, in one scenario, the highest level exception handler in the call stack hierarchy catches all exceptions thrown by lower-level exception handlers.</span></span> <span data-ttu-id="cf328-353">如果存在具有特定键的键/值对，高级别的异常处理程序设置中的剩余键/值对格式<xref:System.Collections.IDictionary>对象以某种使用了非标准方式; 否则为剩余的键/值对的格式以某种正常方式。</span><span class="sxs-lookup"><span data-stu-id="cf328-353">If a key/value pair with a special key exists, the high-level exception handler formats the remaining key/value pairs in the <xref:System.Collections.IDictionary> object in some nonstandard way; otherwise, the remaining key/value pairs are formatted in some normal manner.</span></span>  
  
 <span data-ttu-id="cf328-354">现在假设，在另一个方案中，在每个调用堆栈层次结构级别的异常处理程序会捕获由下一个较低级别的异常处理程序引发的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-354">Now suppose, in another scenario, the exception handler at each level of the call stack hierarchy catches the exception thrown by the next lower-level exception handler.</span></span> <span data-ttu-id="cf328-355">此外，每个异常处理程序知道返回的集合<xref:System.Exception.Data%2A>属性包含与一组预先安排的密钥可访问的键/值对一组。</span><span class="sxs-lookup"><span data-stu-id="cf328-355">In addition, each exception handler knows the collection returned by the <xref:System.Exception.Data%2A> property contains a set of key/value pairs that can be accessed with a prearranged set of keys.</span></span>  
  
 <span data-ttu-id="cf328-356">每个异常处理程序使用预先安排的键集来为该异常处理程序的唯一信息更新相应的键/值对的值组件。</span><span class="sxs-lookup"><span data-stu-id="cf328-356">Each exception handler uses the prearranged set of keys to update the value component of the corresponding key/value pair with information unique to that exception handler.</span></span> <span data-ttu-id="cf328-357">更新过程完成后，异常处理程序将引发下一个更高级别的异常处理程序的例外。</span><span class="sxs-lookup"><span data-stu-id="cf328-357">After the update process is complete, the exception handler throws the exception to the next higher-level exception handler.</span></span> <span data-ttu-id="cf328-358">最后，最高级别的异常处理程序访问的键/值对，并显示来自所有较低级别的异常处理程序的合并的更新信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-358">Finally, the highest level exception handler accesses the key/value pairs and displays the consolidated update information from all the lower-level exception handlers.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-359">下面的示例演示如何添加和检索信息使用<xref:System.Exception.Data%2A>属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-359">The following example demonstrates how to add and retrieve information using the <xref:System.Exception.Data%2A> property.</span></span>  
  
 [!code-cpp[exception.data#1](~/samples/snippets/cpp/VS_Snippets_CLR/exception.data/CPP/data.cpp#1)]
 [!code-csharp[exception.data#1](~/samples/snippets/csharp/VS_Snippets_CLR/exception.data/CS/data.cs#1)]
 [!code-vb[exception.data#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/exception.data/VB/data.vb#1)]  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Collections.DictionaryEntry" />
      </Docs>
    </Member>
    <Member MemberName="GetBaseException">
      <MemberSignature Language="C#" Value="public virtual Exception GetBaseException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig newslot virtual instance class System.Exception GetBaseException() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.GetBaseException" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Function GetBaseException () As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual Exception ^ GetBaseException();" />
      <MemberSignature Language="F#" Value="abstract member GetBaseException : unit -&gt; Exception&#xA;override this.GetBaseException : unit -&gt; Exception" Usage="exception.GetBaseException " />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.GetBaseException</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="cf328-360">当在派生类中重写时，返回 <see cref="T:System.Exception" />，它是一个或多个并发的异常的根本原因。</span><span class="sxs-lookup"><span data-stu-id="cf328-360">When overridden in a derived class, returns the <see cref="T:System.Exception" /> that is the root cause of one or more subsequent exceptions.</span></span></summary>
        <returns><span data-ttu-id="cf328-361">异常链中第一个被引发的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-361">The first exception thrown in a chain of exceptions.</span></span> <span data-ttu-id="cf328-362">如果当前异常的 <see cref="P:System.Exception.InnerException" /> 属性是 null 引用（Visual Basic 中为 <see langword="Nothing" />），则此属性返回当前异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-362">If the <see cref="P:System.Exception.InnerException" /> property of the current exception is a null reference (<see langword="Nothing" /> in Visual Basic), this property returns the current exception.</span></span></returns>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-363">异常链包含一组异常，以便为引用中的异常的直接结果引发链中的每个异常其`InnerException`属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-363">A chain of exceptions consists of a set of exceptions such that each exception in the chain was thrown as a direct result of the exception referenced in its `InnerException` property.</span></span> <span data-ttu-id="cf328-364">对于给定的链，可以有且只有一个是链中的其他所有异常的根本原因的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-364">For a given chain, there can be exactly one exception that is the root cause of all other exceptions in the chain.</span></span> <span data-ttu-id="cf328-365">此异常被称为基异常并将其`InnerException`属性始终包含一个 null 引用。</span><span class="sxs-lookup"><span data-stu-id="cf328-365">This exception is called the base exception and its `InnerException` property always contains a null reference.</span></span>  
  
 <span data-ttu-id="cf328-366">所有异常的异常，链中`GetBaseException`方法必须返回相同的对象 （基异常）。</span><span class="sxs-lookup"><span data-stu-id="cf328-366">For all exceptions in a chain of exceptions, the `GetBaseException` method must return the same object (the base exception).</span></span>  
  
 <span data-ttu-id="cf328-367">使用`GetBaseException`方法时您想要查找异常的根本原因，但是不需要有关当前异常和第一个异常之间可能发生的异常的信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-367">Use the `GetBaseException` method when you want to find the root cause of an exception but do not need information about exceptions that may have occurred between the current exception and the first exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-368">下面的代码示例定义了两个派生`Exception`类。</span><span class="sxs-lookup"><span data-stu-id="cf328-368">The following code example defines two derived `Exception` classes.</span></span> <span data-ttu-id="cf328-369">它强制异常，然后在与每个派生的类重新引发它。</span><span class="sxs-lookup"><span data-stu-id="cf328-369">It forces an exception and then throws it again with each of the derived classes.</span></span> <span data-ttu-id="cf328-370">该代码演示如何使用`GetBaseException`方法来检索原始异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-370">The code shows the use of the `GetBaseException` method to retrieve the original exception.</span></span>  
  
 [!code-cpp[System.Exception.GetBaseException#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.GetBaseException/CPP/getbaseexc.cpp#1)]
 [!code-csharp[System.Exception.GetBaseException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.GetBaseException/CS/getbaseexc.cs#1)]
 [!code-vb[System.Exception.GetBaseException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.GetBaseException/VB/getbaseexc.vb#1)]  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides"><para><span data-ttu-id="cf328-371"><see langword="GetBaseException" />需要控制异常的内容或格式的类中重写方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-371">The <see langword="GetBaseException" /> method is overridden in classes that require control over the exception content or format.</span></span></para></block>
      </Docs>
    </Member>
    <Member MemberName="GetObjectData">
      <MemberSignature Language="C#" Value="public virtual void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig newslot virtual instance void GetObjectData(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Sub GetObjectData (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual void GetObjectData(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="abstract member GetObjectData : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; unit&#xA;override this.GetObjectData : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; unit" Usage="exception.GetObjectData (info, context)" />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)</InterfaceMember>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
          <AttributeName>System.Security.SecurityCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Void</ReturnType>
      </ReturnValue>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="cf328-372">包含有关所引发异常的序列化对象数据的 <see cref="T:System.Runtime.Serialization.SerializationInfo" />。</span><span class="sxs-lookup"><span data-stu-id="cf328-372">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</span></span></param>
        <param name="context"><span data-ttu-id="cf328-373"><see cref="T:System.Runtime.Serialization.StreamingContext" />，它包含关于源或目标的上下文信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-373">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="cf328-374">当在派生类中重写时，用关于异常的信息设置 <see cref="T:System.Runtime.Serialization.SerializationInfo" />。</span><span class="sxs-lookup"><span data-stu-id="cf328-374">When overridden in a derived class, sets the <see cref="T:System.Runtime.Serialization.SerializationInfo" /> with information about the exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-375">`GetObjectData` 使用针对于序列化的所有异常对象数据设置 <xref:System.Runtime.Serialization.SerializationInfo>。</span><span class="sxs-lookup"><span data-stu-id="cf328-375">`GetObjectData` sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization.</span></span> <span data-ttu-id="cf328-376">反序列化期间，从通过流传输的 `SerializationInfo` 重建异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-376">During deserialization, the exception is reconstituted from the `SerializationInfo` transmitted over the stream.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-377">下面的代码示例定义一个派生可序列化`Exception`类，该类实现`GetObjectData`这两个属性对进行次要更改，然后调用基类来执行序列化。</span><span class="sxs-lookup"><span data-stu-id="cf328-377">The following code example defines a derived serializable `Exception` class that implements `GetObjectData`, which makes minor changes to two properties and then calls the base class to perform the serialization.</span></span> <span data-ttu-id="cf328-378">该示例会强制由零除错误，然后创建派生的异常的实例。</span><span class="sxs-lookup"><span data-stu-id="cf328-378">The example forces a divide-by-0 error and then creates an instance of the derived exception.</span></span> <span data-ttu-id="cf328-379">代码序列化到文件的实例，则反文件序列化为一个新的异常，则会引发，然后捕获并显示异常的数据。</span><span class="sxs-lookup"><span data-stu-id="cf328-379">The code serializes the instance to a file, deserializes the file into a new exception, which it throws, and then catches and displays the exception's data.</span></span>  
  
 [!code-cpp[System.Exception.GetObjectData#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CPP/getobjdata.cpp#1)]
 [!code-csharp[System.Exception.GetObjectData#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CS/getobjdata.cs#1)]
 [!code-vb[System.Exception.GetObjectData#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.GetObjectData/VB/getobjdata.vb#1)]  
  
 ]]></format>
        </remarks>
        <exception cref="T:System.ArgumentNullException"><span data-ttu-id="cf328-380"><paramref name="info" /> 参数为 null 引用（在 Visual Basic 中为 <see langword="Nothing" />）。</span><span class="sxs-lookup"><span data-stu-id="cf328-380">The <paramref name="info" /> parameter is a null reference (<see langword="Nothing" /> in Visual Basic).</span></span></exception>
        <permission cref="T:System.Security.SecurityCriticalAttribute"><span data-ttu-id="cf328-381">直接调用方需要完全信任。</span><span class="sxs-lookup"><span data-stu-id="cf328-381">requires full trust for the immediate caller.</span></span> <span data-ttu-id="cf328-382">不能由部分受信任的或透明的代码使用此成员。</span><span class="sxs-lookup"><span data-stu-id="cf328-382">This member cannot be used by partially trusted or transparent code.</span></span></permission>
        <altmember cref="T:System.Runtime.Serialization.SerializationInfo" />
        <altmember cref="T:System.Runtime.Serialization.StreamingContext" />
      </Docs>
    </Member>
    <Member MemberName="GetType">
      <MemberSignature Language="C#" Value="public Type GetType ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig newslot virtual instance class System.Type GetType() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.GetType" />
      <MemberSignature Language="VB.NET" Value="Public Function GetType () As Type" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual Type ^ GetType();" />
      <MemberSignature Language="F#" Value="override this.GetType : unit -&gt; Type" Usage="exception.GetType " />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.GetType</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Type</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="cf328-383">获取当前实例的运行时类型。</span><span class="sxs-lookup"><span data-stu-id="cf328-383">Gets the runtime type of the current instance.</span></span></summary>
        <returns><span data-ttu-id="cf328-384">一个 <see cref="T:System.Type" /> 对象，表示当前实例的确切运行时类型。</span><span class="sxs-lookup"><span data-stu-id="cf328-384">A <see cref="T:System.Type" /> object that represents the exact runtime type of the current instance.</span></span></returns>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-385"><xref:System.Exception.GetType%2A>方法存在是为了支持.NET Framework 基础结构，并在内部调用的基本方法<xref:System.Object.GetType%2A?displayProperty=nameWithType>。</span><span class="sxs-lookup"><span data-stu-id="cf328-385">The <xref:System.Exception.GetType%2A> method exists to support the .NET Framework infrastructure, and internally invokes the fundamental method, <xref:System.Object.GetType%2A?displayProperty=nameWithType>.</span></span>  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Type" />
        <altmember cref="T:System.Object" />
      </Docs>
    </Member>
    <Member MemberName="HelpLink">
      <MemberSignature Language="C#" Value="public virtual string HelpLink { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string HelpLink" />
      <MemberSignature Language="DocId" Value="P:System.Exception.HelpLink" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Property HelpLink As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ HelpLink { System::String ^ get(); void set(System::String ^ value); };" />
      <MemberSignature Language="F#" Value="member this.HelpLink : string with get, set" Usage="System.Exception.HelpLink" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.HelpLink</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-386">获取或设置指向与此异常关联的帮助文件链接。</span><span class="sxs-lookup"><span data-stu-id="cf328-386">Gets or sets a link to the help file associated with this exception.</span></span></summary>
        <value><span data-ttu-id="cf328-387">统一资源名称 (URN) 或统一资源定位器 (URL)。</span><span class="sxs-lookup"><span data-stu-id="cf328-387">The Uniform Resource Name (URN) or Uniform Resource Locator (URL).</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-388">表示帮助文件的返回值是 URN 或 URL。</span><span class="sxs-lookup"><span data-stu-id="cf328-388">The return value, which represents a help file, is a URN or URL.</span></span> <span data-ttu-id="cf328-389">例如，`HelpLink`值可以是：</span><span class="sxs-lookup"><span data-stu-id="cf328-389">For example, the `HelpLink` value could be:</span></span>  
  
 <span data-ttu-id="cf328-390">"file:///C:/Applications/Bazzal/help.html#ErrorNum42"</span><span class="sxs-lookup"><span data-stu-id="cf328-390">"file:///C:/Applications/Bazzal/help.html#ErrorNum42"</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-391">下面的代码示例，则会引发`Exception`，用于设置`HelpLink`属性在其构造函数，然后捕捉异常并显示`HelpLink`。</span><span class="sxs-lookup"><span data-stu-id="cf328-391">The following code example throws an `Exception` that sets the `HelpLink` property in its constructor and then catches the exception and displays `HelpLink`.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="HResult">
      <MemberSignature Language="C#" Value="public int HResult { get; protected set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance int32 HResult" />
      <MemberSignature Language="DocId" Value="P:System.Exception.HResult" />
      <MemberSignature Language="VB.NET" Value="Public Property HResult As Integer" />
      <MemberSignature Language="C++ CLI" Value="public:  property int HResult {  public:&#xA;int get(); protected:&#xA; void set(int value); };" />
      <MemberSignature Language="F#" Value="member this.HResult : int with get, set" Usage="System.Exception.HResult" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Int32</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-392">获取或设置 HRESULT（一个分配给特定异常的编码数字值）。</span><span class="sxs-lookup"><span data-stu-id="cf328-392">Gets or sets HRESULT, a coded numerical value that is assigned to a specific exception.</span></span></summary>
        <value><span data-ttu-id="cf328-393">HRESULT 值。</span><span class="sxs-lookup"><span data-stu-id="cf328-393">The HRESULT value.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-394">HRESULT 是一个 32 位值，划分为三个不同的字段： 一个严重性代码、 一个设备代码和错误代码。</span><span class="sxs-lookup"><span data-stu-id="cf328-394">HRESULT is a 32-bit value, divided into three different fields: a severity code, a facility code, and an error code.</span></span> <span data-ttu-id="cf328-395">严重性代码指示返回的值表示信息、 警告或错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-395">The severity code indicates whether the return value represents information, warning, or error.</span></span> <span data-ttu-id="cf328-396">设备代码标识导致错误的系统的区域。</span><span class="sxs-lookup"><span data-stu-id="cf328-396">The facility code identifies the area of the system responsible for the error.</span></span> <span data-ttu-id="cf328-397">错误代码是分配来表示异常的唯一编号。</span><span class="sxs-lookup"><span data-stu-id="cf328-397">The error code is a unique number that is assigned to represent the exception.</span></span> <span data-ttu-id="cf328-398">每个异常映射到不同的 HRESULT。</span><span class="sxs-lookup"><span data-stu-id="cf328-398">Each exception is mapped to a distinct HRESULT.</span></span> <span data-ttu-id="cf328-399">当托管的代码引发异常时，运行时将 HRESULT 传递给 COM 客户端。</span><span class="sxs-lookup"><span data-stu-id="cf328-399">When managed code throws an exception, the runtime passes the HRESULT to the COM client.</span></span> <span data-ttu-id="cf328-400">当非托管的代码将返回错误时，HRESULT 转换为异常，则引发运行时。</span><span class="sxs-lookup"><span data-stu-id="cf328-400">When unmanaged code returns an error, the HRESULT is converted to an exception, which is then thrown by the runtime.</span></span> <span data-ttu-id="cf328-401">有关 HRESULT 值和其相应的.NET Framework 异常的信息，请参阅[如何： 映射 Hresult 和异常](~/docs/framework/interop/how-to-map-hresults-and-exceptions.md)。</span><span class="sxs-lookup"><span data-stu-id="cf328-401">For information about HRESULT values and their corresponding .NET Framework exceptions, see [How to: Map HRESULTs and Exceptions](~/docs/framework/interop/how-to-map-hresults-and-exceptions.md).</span></span> <span data-ttu-id="cf328-402">请参阅[常见的 HRESULT 值](https://msdn.microsoft.com/library/windows/desktop/aa378137.aspx)中最有可能会遇到的值列表的 Windows 文档。</span><span class="sxs-lookup"><span data-stu-id="cf328-402">See [Common HRESULT Values](https://msdn.microsoft.com/library/windows/desktop/aa378137.aspx) in the Windows documentation for a list of the values you are most likely to encounter.</span></span>  
  
 <span data-ttu-id="cf328-403">从开始[!INCLUDE[net_v45](~/includes/net-v45-md.md)]，则<xref:System.Exception.HResult%2A>属性的 setter 受到保护，而其 getter 是公共的。</span><span class="sxs-lookup"><span data-stu-id="cf328-403">Starting with the [!INCLUDE[net_v45](~/includes/net-v45-md.md)], the <xref:System.Exception.HResult%2A> property's setter is protected, whereas its getter is public.</span></span>  <span data-ttu-id="cf328-404">在以前版本的.NET Framework，getter 和 setter 进行保护。</span><span class="sxs-lookup"><span data-stu-id="cf328-404">In previous versions of the .NET Framework, both getter and setter are protected.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-405">下面的代码示例定义一个派生`Exception`类，用于设置`HResult`属性在其构造函数中的自定义值。</span><span class="sxs-lookup"><span data-stu-id="cf328-405">The following code example defines a derived `Exception` class that sets the `HResult` property to a custom value in its constructor.</span></span>  
  
 [!code-cpp[System.Exception.HResult#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.HResult/CPP/hresult.cpp#1)]
 [!code-csharp[System.Exception.HResult#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.HResult/CS/hresult.cs#1)]
 [!code-vb[System.Exception.HResult#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.HResult/VB/hresult.vb#1)]  
  
 ]]></format>
        </remarks>
        <related type="Article" href="https://msdn.microsoft.com/library/610b364b-2761-429d-9c4a-afbc3e66f1b9"><span data-ttu-id="cf328-406">如何：映射 HRESULT 和异常</span><span class="sxs-lookup"><span data-stu-id="cf328-406">How to: Map HRESULTs and Exceptions</span></span></related>
        <related type="ExternalDocumentation" href="https://msdn.microsoft.com/library/windows/desktop/aa378137.aspx"><span data-ttu-id="cf328-407">常见的 HRESULT 值</span><span class="sxs-lookup"><span data-stu-id="cf328-407">Common HRESULT Values</span></span></related>
      </Docs>
    </Member>
    <Member MemberName="InnerException">
      <MemberSignature Language="C#" Value="public Exception InnerException { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception InnerException" />
      <MemberSignature Language="DocId" Value="P:System.Exception.InnerException" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property InnerException As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ InnerException { Exception ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.InnerException : Exception" Usage="System.Exception.InnerException" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.InnerException</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-408">获取导致当前异常的 <see cref="T:System.Exception" /> 实例。</span><span class="sxs-lookup"><span data-stu-id="cf328-408">Gets the <see cref="T:System.Exception" /> instance that caused the current exception.</span></span></summary>
        <value><span data-ttu-id="cf328-409">描述导致当前异常的错误的一个对象。</span><span class="sxs-lookup"><span data-stu-id="cf328-409">An object that describes the error that caused the current exception.</span></span> <span data-ttu-id="cf328-410"><see cref="P:System.Exception.InnerException" /> 属性返回的值与传递到 <see cref="M:System.Exception.#ctor(System.String,System.Exception)" /> 构造函数中的值相同，如果没有向构造函数提供内部异常值，则为 <see langword="null" />。</span><span class="sxs-lookup"><span data-stu-id="cf328-410">The <see cref="P:System.Exception.InnerException" /> property returns the same value as was passed into the <see cref="M:System.Exception.#ctor(System.String,System.Exception)" /> constructor, or <see langword="null" /> if the inner exception value was not supplied to the constructor.</span></span> <span data-ttu-id="cf328-411">此属性是只读的。</span><span class="sxs-lookup"><span data-stu-id="cf328-411">This property is read-only.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-412">当异常`X`作为前一个异常的直接结果引发`Y`，则<xref:System.Exception.InnerException%2A>的属性`X`应包含对引用`Y`。</span><span class="sxs-lookup"><span data-stu-id="cf328-412">When an exception `X` is thrown as a direct result of a previous exception `Y`, the <xref:System.Exception.InnerException%2A> property of `X` should contain a reference to `Y`.</span></span>  
  
 <span data-ttu-id="cf328-413">使用 <xref:System.Exception.InnerException%2A> 属性获取导致当前异常的异常集。</span><span class="sxs-lookup"><span data-stu-id="cf328-413">Use the <xref:System.Exception.InnerException%2A> property to obtain the set of exceptions that led to the current exception.</span></span>  
  
 <span data-ttu-id="cf328-414">您可以创建一个新的异常捕获的早期异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-414">You can create a new exception that catches an earlier exception.</span></span> <span data-ttu-id="cf328-415">处理第二个异常可以用于从以前的异常的附加信息更恰当地处理错误代码。</span><span class="sxs-lookup"><span data-stu-id="cf328-415">The code that handles the second exception can make use of the additional information from the earlier exception to handle the error more appropriately.</span></span>  
  
 <span data-ttu-id="cf328-416">假定有一个函数，读取文件，并从该文件数据的格式。</span><span class="sxs-lookup"><span data-stu-id="cf328-416">Suppose that there is a function that reads a file and formats the data from that file.</span></span> <span data-ttu-id="cf328-417">在此示例中，代码尝试读取该文件，作为<xref:System.IO.IOException>引发。</span><span class="sxs-lookup"><span data-stu-id="cf328-417">In this example, as the code tries to read the file, an <xref:System.IO.IOException> is thrown.</span></span> <span data-ttu-id="cf328-418">该函数会捕获<xref:System.IO.IOException>，并引发<xref:System.IO.FileNotFoundException>。</span><span class="sxs-lookup"><span data-stu-id="cf328-418">The function catches the <xref:System.IO.IOException> and throws a <xref:System.IO.FileNotFoundException>.</span></span> <span data-ttu-id="cf328-419"><xref:System.IO.IOException>未能在保存<xref:System.Exception.InnerException%2A>的属性<xref:System.IO.FileNotFoundException>，启用捕获的代码<xref:System.IO.FileNotFoundException>来检查初始错误的原因。</span><span class="sxs-lookup"><span data-stu-id="cf328-419">The <xref:System.IO.IOException> could be saved in the <xref:System.Exception.InnerException%2A> property of the <xref:System.IO.FileNotFoundException>, enabling the code that catches the <xref:System.IO.FileNotFoundException> to examine the cause of the initial error.</span></span>  
  
 <span data-ttu-id="cf328-420"><xref:System.Exception.InnerException%2A>属性，保存对内部异常的引用，该属性设置的异常对象初始化时。</span><span class="sxs-lookup"><span data-stu-id="cf328-420">The <xref:System.Exception.InnerException%2A> property, which holds a reference to the inner exception, is set upon initialization of the exception object.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-421">下面的示例演示如何引发和捕获引用内部异常的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-421">The following example demonstrates throwing and catching an exception that references an inner exception.</span></span>  
  
 [!code-cpp[InnerEx#1](~/samples/snippets/cpp/VS_Snippets_CLR/InnerEx/CPP/innerex.cpp#1)]
 [!code-csharp[InnerEx#1](~/samples/snippets/csharp/VS_Snippets_CLR/InnerEx/CS/innerex.cs#1)]
 [!code-vb[InnerEx#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/InnerEx/VB/innerex.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Message">
      <MemberSignature Language="C#" Value="public virtual string Message { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string Message" />
      <MemberSignature Language="DocId" Value="P:System.Exception.Message" />
      <MemberSignature Language="VB.NET" Value="Public Overridable ReadOnly Property Message As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ Message { System::String ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Message : string" Usage="System.Exception.Message" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.Message</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>get: System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-422">获取描述当前异常的消息。</span><span class="sxs-lookup"><span data-stu-id="cf328-422">Gets a message that describes the current exception.</span></span></summary>
        <value><span data-ttu-id="cf328-423">解释异常原因的错误消息或空字符串 ("")。</span><span class="sxs-lookup"><span data-stu-id="cf328-423">The error message that explains the reason for the exception, or an empty string ("").</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-424">错误消息为目标的开发人员处理异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-424">Error messages target the developer who is handling the exception.</span></span> <span data-ttu-id="cf328-425">文本<xref:System.Exception.Message%2A>属性应当完整地描述该错误，并在可能的情况下，还应说明如何更正此错误。</span><span class="sxs-lookup"><span data-stu-id="cf328-425">The text of the <xref:System.Exception.Message%2A> property should completely describe the error and, when possible, should also explain how to correct the error.</span></span> <span data-ttu-id="cf328-426">顶级异常处理程序可能会向最终用户，显示该消息，因此应确保它的语法正确，并且消息的每个句子有以句点结尾。</span><span class="sxs-lookup"><span data-stu-id="cf328-426">Top-level exception handlers may display the message to end-users, so you should ensure that it is grammatically correct and that each sentence of the message ends with a period.</span></span> <span data-ttu-id="cf328-427">不要使用问号或感叹号。</span><span class="sxs-lookup"><span data-stu-id="cf328-427">Do not use question marks or exclamation points.</span></span> <span data-ttu-id="cf328-428">如果你的应用程序使用本地化的异常消息，应确保它们准确地转换。</span><span class="sxs-lookup"><span data-stu-id="cf328-428">If your application uses localized exception messages, you should ensure that they are accurately translated.</span></span>  
  
> [!IMPORTANT]
>  <span data-ttu-id="cf328-429">而不检查相应的权限不披露异常消息中的敏感信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-429">Do not disclose sensitive information in exception messages without checking for the appropriate permissions.</span></span>  
  
 <span data-ttu-id="cf328-430">值<xref:System.Exception.Message%2A>属性包含在返回的信息<xref:System.Exception.ToString%2A>。<xref:System.Exception.Message%2A>属性仅在创建时设置<xref:System.Exception>。</span><span class="sxs-lookup"><span data-stu-id="cf328-430">The value of the <xref:System.Exception.Message%2A> property is included in the information returned by <xref:System.Exception.ToString%2A>.The <xref:System.Exception.Message%2A> property is set only when creating an <xref:System.Exception>.</span></span> <span data-ttu-id="cf328-431">如果没有消息提供给当前实例的构造函数，则系统将提供的默认消息使用当前系统区域性进行格式化。</span><span class="sxs-lookup"><span data-stu-id="cf328-431">If no message was supplied to the constructor for the current instance, the system supplies a default message that is formatted using the current system culture.</span></span>  
  
## <a name="windows-runtime-and-includenetv451includesnet-v451-mdmd"></a><span data-ttu-id="cf328-432">Windows 运行时和 [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span><span class="sxs-lookup"><span data-stu-id="cf328-432">Windows Runtime and [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span></span>  
 <span data-ttu-id="cf328-433">从开始[!INCLUDE[net_v451](~/includes/net-v451-md.md)]和[!INCLUDE[win81](~/includes/win81-md.md)]，改进了从 Windows 运行时类型和成员的不是.NET Framework 的一部分从传播的异常错误消息的保真度。</span><span class="sxs-lookup"><span data-stu-id="cf328-433">Starting with the [!INCLUDE[net_v451](~/includes/net-v451-md.md)] and [!INCLUDE[win81](~/includes/win81-md.md)], the fidelity of error messages from exceptions that are propagated from Windows Runtime types and members that are not part of the .NET Framework is improved.</span></span> <span data-ttu-id="cf328-434">具体而言，异常消息从 Visual c + + 组件扩展 (C + + /cli CX) 现在传播回.NET Framework<xref:System.Exception>对象。</span><span class="sxs-lookup"><span data-stu-id="cf328-434">In particular, exception messages from Visual C++ component extensions (C++/CX) are now propagated back into .NET Framework <xref:System.Exception> objects.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-435">下面的代码示例将引发，然后<xref:System.Exception>异常，并显示异常的文本消息使用<xref:System.Exception.Message%2A>属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-435">The following code example throws and then catches an <xref:System.Exception> exception and displays the exception's text message using the <xref:System.Exception.Message%2A> property.</span></span>
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides"><para><span data-ttu-id="cf328-436">如果引发异常的属性，并且需要进行的文本中，请参阅<see cref="P:System.Exception.Message" />到设置或获取的属性参数，将"值"用作属性参数的名称。</span><span class="sxs-lookup"><span data-stu-id="cf328-436">If you throw an exception from a property, and you need to refer in the text of <see cref="P:System.Exception.Message" /> to the property argument that you set or get, use "value" as the name of the property argument.</span></span></para></block>
        <block subset="none" type="overrides"><para><span data-ttu-id="cf328-437"><see cref="P:System.Exception.Message" />需要控制消息内容或格式的类中重写属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-437">The <see cref="P:System.Exception.Message" /> property is overridden in classes that require control over message content or format.</span></span> <span data-ttu-id="cf328-438">需要显示有关已捕获异常的信息时，应用程序代码通常会访问此属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-438">Application code typically accesses this property when it needs to display information about an exception that has been caught.</span></span>  
  
<span data-ttu-id="cf328-439">应本地化错误消息。</span><span class="sxs-lookup"><span data-stu-id="cf328-439">The error message should be localized.</span></span></para></block>
      </Docs>
    </Member>
    <Member MemberName="SerializeObjectState">
      <MemberSignature Language="C#" Value="protected event EventHandler&lt;System.Runtime.Serialization.SafeSerializationEventArgs&gt; SerializeObjectState;" />
      <MemberSignature Language="ILAsm" Value=".event class System.EventHandler`1&lt;class System.Runtime.Serialization.SafeSerializationEventArgs&gt; SerializeObjectState" />
      <MemberSignature Language="DocId" Value="E:System.Exception.SerializeObjectState" />
      <MemberSignature Language="VB.NET" Value="Protected Custom Event SerializeObjectState As EventHandler(Of SafeSerializationEventArgs) " />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; event EventHandler&lt;System::Runtime::Serialization::SafeSerializationEventArgs ^&gt; ^ SerializeObjectState;" />
      <MemberSignature Language="F#" Value="member this.SerializeObjectState : EventHandler&lt;System.Runtime.Serialization.SafeSerializationEventArgs&gt; " Usage="member this.SerializeObjectState : System.EventHandler&lt;System.Runtime.Serialization.SafeSerializationEventArgs&gt; " />
      <MemberType>Event</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.EventHandler&lt;System.Runtime.Serialization.SafeSerializationEventArgs&gt;</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-440">当异常被序列化用来创建包含有关该异常的徐列出数据的异常状态对象时会出现该问题。</span><span class="sxs-lookup"><span data-stu-id="cf328-440">Occurs when an exception is serialized to create an exception state object that contains serialized data about the exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-441">异常状态对象实现<xref:System.Runtime.Serialization.ISafeSerializationData>接口。</span><span class="sxs-lookup"><span data-stu-id="cf328-441">The exception state object implements the <xref:System.Runtime.Serialization.ISafeSerializationData> interface.</span></span>  
  
 <span data-ttu-id="cf328-442">当<xref:System.Exception.SerializeObjectState>订阅事件时，此异常将反序列化并创建为空的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-442">When the <xref:System.Exception.SerializeObjectState> event is subscribed to, the exception is deserialized and created as an empty exception.</span></span> <span data-ttu-id="cf328-443">异常的构造函数时不运行，并且还反序列化的异常状态。</span><span class="sxs-lookup"><span data-stu-id="cf328-443">The exception's constructor is not run, and the exception state is also deserialized.</span></span> <span data-ttu-id="cf328-444"><xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A>异常状态对象的回调方法然后通知，以便它可以将反序列化的数据推送到空的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-444">The <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A> callback method of the exception state object is then notified so that it can push deserialized data into the empty exception.</span></span>  
  
 <span data-ttu-id="cf328-445"><xref:System.Exception.SerializeObjectState>事件使透明异常类型进行序列化和反序列化异常数据。</span><span class="sxs-lookup"><span data-stu-id="cf328-445">The <xref:System.Exception.SerializeObjectState> event enables transparent exception types to serialize and deserialize exception data.</span></span> <span data-ttu-id="cf328-446">透明代码可以执行命令，在其运行的权限集的边界内，但不能执行、 调用、 派生，或包含关键代码。</span><span class="sxs-lookup"><span data-stu-id="cf328-446">Transparent code can execute commands within the bounds of the permission set it is operating within, but cannot execute, call, derive from, or contain critical code.</span></span>  
  
 <span data-ttu-id="cf328-447">如果<xref:System.Exception.SerializeObjectState>事件未订阅，像往常一样使用反序列化时发生<xref:System.Exception.%23ctor%2A>构造函数。</span><span class="sxs-lookup"><span data-stu-id="cf328-447">If the <xref:System.Exception.SerializeObjectState> event is not subscribed to, deserialization occurs as usual using the <xref:System.Exception.%23ctor%2A> constructor.</span></span>  
  
 <span data-ttu-id="cf328-448">通常情况下，处理程序<xref:System.Exception.SerializeObjectState>异常的构造函数提供的序列化过程中添加事件。</span><span class="sxs-lookup"><span data-stu-id="cf328-448">Typically, a handler for the <xref:System.Exception.SerializeObjectState> event is added in the exception's constructor to provide for its serialization.</span></span> <span data-ttu-id="cf328-449">但是，由于构造函数不是执行时<xref:System.Exception.SerializeObjectState>事件处理程序执行时，序列化反序列化的异常可能会引发<xref:System.Runtime.Serialization.SerializationException>时尝试反序列化异常的异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-449">But because the constructor is not executed when the <xref:System.Exception.SerializeObjectState> event handler executes, serializing a deserialized exception can throw a <xref:System.Runtime.Serialization.SerializationException> exception when you try to deserialize the exception.</span></span> <span data-ttu-id="cf328-450">若要避免此问题，您应添加的处理程序<xref:System.Exception.SerializeObjectState>中的事件<xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType>方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-450">To avoid this, you should also add the handler for the <xref:System.Exception.SerializeObjectState> event in the <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType> method.</span></span> <span data-ttu-id="cf328-451">请参阅示例部分的说明。</span><span class="sxs-lookup"><span data-stu-id="cf328-451">See the Examples section for an illustration.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-452">下面的示例定义`BadDivisionException`用于处理<xref:System.Exception.SerializeObjectState>事件。</span><span class="sxs-lookup"><span data-stu-id="cf328-452">The following example defines a `BadDivisionException` that handles the <xref:System.Exception.SerializeObjectState> event.</span></span> <span data-ttu-id="cf328-453">它还包含一个状态对象，它是嵌套结构名为`BadDivisionExceptionState`实现<xref:System.Runtime.Serialization.ISafeSerializationData>接口。</span><span class="sxs-lookup"><span data-stu-id="cf328-453">It also contains a state object, which is a nested structure named `BadDivisionExceptionState` that implements the <xref:System.Runtime.Serialization.ISafeSerializationData> interface.</span></span>  
  
 [!code-csharp[System.Exception.SerializeObjectState#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.serializeobjectstate/cs/example2.cs#1)]
 [!code-vb[System.Exception.SerializeObjectState#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.serializeobjectstate/vb/example2.vb#1)]  
  
 <span data-ttu-id="cf328-454">`BadDivisionException`浮点除数为零发生时引发异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-454">The `BadDivisionException` exception is thrown when a floating-point division by zero occurs.</span></span> <span data-ttu-id="cf328-455">在第一个除数为零，该示例实例化`BadDivisionException`对象，将其，序列化，则引发异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-455">During the first division by zero, the example instantiates a `BadDivisionException` object, serializes it, and throws the exception.</span></span> <span data-ttu-id="cf328-456">出现被零后续部门，示例反序列化之前序列化的对象、 重新序列化该它，并引发异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-456">When subsequent divisions by zero occur, the example deserializes the  previously serialized object, reserializes it, and throws the exception.</span></span> <span data-ttu-id="cf328-457">若要提供的对象序列化、 反序列化、 重新，序列化和反序列化，该示例将添加<xref:System.Exception.SerializeObjectState>中的事件处理程序这两个`BadDivisionException`类构造函数并在<xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType>实现。</span><span class="sxs-lookup"><span data-stu-id="cf328-457">To provide for object serialization, deserialization, reserialization, and deserialization, the example adds the <xref:System.Exception.SerializeObjectState> event handler both in the `BadDivisionException` class constructor and in the <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType> implementation.</span></span>  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides"><para><span data-ttu-id="cf328-458">如果此事件是订阅和使用，请遵循中的继承层次结构的所有派生的类型必须实现相同的序列化机制。</span><span class="sxs-lookup"><span data-stu-id="cf328-458">If this event is subscribed to and used, all derived types that follow in the inheritance hierarchy must implement the same serialization mechanism.</span></span></para></block>
      </Docs>
    </Member>
    <Member MemberName="Source">
      <MemberSignature Language="C#" Value="public virtual string Source { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string Source" />
      <MemberSignature Language="DocId" Value="P:System.Exception.Source" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Property Source As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ Source { System::String ^ get(); void set(System::String ^ value); };" />
      <MemberSignature Language="F#" Value="member this.Source : string with get, set" Usage="System.Exception.Source" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.Source</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>get: System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-459">获取或设置导致错误的应用程序或对象的名称。</span><span class="sxs-lookup"><span data-stu-id="cf328-459">Gets or sets the name of the application or the object that causes the error.</span></span></summary>
        <value><span data-ttu-id="cf328-460">导致错误的应用程序或对象的名称。</span><span class="sxs-lookup"><span data-stu-id="cf328-460">The name of the application or the object that causes the error.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-461">如果<xref:System.Exception.Source%2A>属性未显式设置，则运行时自动将其设置为产生异常的程序集的名称。</span><span class="sxs-lookup"><span data-stu-id="cf328-461">If the <xref:System.Exception.Source%2A> property is not set explicitly, the runtime automatically sets it to the name of the assembly in which the exception originated.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-462">下面的示例将引发`Exception`，用于设置`Source`属性在其构造函数，然后捕捉异常并显示`Source`。</span><span class="sxs-lookup"><span data-stu-id="cf328-462">The following example throws an `Exception` that sets the `Source` property in its constructor and then catches the exception and displays `Source`.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
        <exception cref="T:System.ArgumentException"><span data-ttu-id="cf328-463">对象必须是运行时 <see cref="N:System.Reflection" /> 对象</span><span class="sxs-lookup"><span data-stu-id="cf328-463">The object must be a runtime <see cref="N:System.Reflection" /> object</span></span></exception>
      </Docs>
    </Member>
    <Member MemberName="StackTrace">
      <MemberSignature Language="C#" Value="public virtual string StackTrace { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string StackTrace" />
      <MemberSignature Language="DocId" Value="P:System.Exception.StackTrace" />
      <MemberSignature Language="VB.NET" Value="Public Overridable ReadOnly Property StackTrace As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ StackTrace { System::String ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.StackTrace : string" Usage="System.Exception.StackTrace" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.StackTrace</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>get: System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-464">获取调用堆栈上的即时框架字符串表示形式。</span><span class="sxs-lookup"><span data-stu-id="cf328-464">Gets a string representation of the immediate frames on the call stack.</span></span></summary>
        <value><span data-ttu-id="cf328-465">用于描述调用堆栈的直接帧的字符串。</span><span class="sxs-lookup"><span data-stu-id="cf328-465">A string that describes the immediate frames of the call stack.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-466">执行堆栈将跟踪在给定时刻正在执行的所有方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-466">The execution stack keeps track of all the methods that are in execution at a given instant.</span></span> <span data-ttu-id="cf328-467">对方法调用的跟踪称为堆栈跟踪。</span><span class="sxs-lookup"><span data-stu-id="cf328-467">A trace of the method calls is called a stack trace.</span></span> <span data-ttu-id="cf328-468">堆栈跟踪列表提供了一种方法的调用堆栈跟踪到方法中的行号出现异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-468">The stack trace listing provides a way to follow the call stack to the line number in the method where the exception occurs.</span></span>  
  
 <span data-ttu-id="cf328-469"><xref:System.Exception.StackTrace%2A>属性返回在引发异常的位置发出的调用堆栈帧。</span><span class="sxs-lookup"><span data-stu-id="cf328-469">The <xref:System.Exception.StackTrace%2A> property returns the frames of the call stack that originate at the location where the exception was thrown.</span></span> <span data-ttu-id="cf328-470">可以通过创建的新实例来获取有关其他帧调用堆栈中的信息<xref:System.Diagnostics.StackTrace?displayProperty=nameWithType>类并使用其<xref:System.Diagnostics.StackTrace.ToString%2A?displayProperty=nameWithType>方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-470">You can obtain information about additional frames in the call stack by creating a new instance of the <xref:System.Diagnostics.StackTrace?displayProperty=nameWithType> class and using its <xref:System.Diagnostics.StackTrace.ToString%2A?displayProperty=nameWithType> method.</span></span>  
  
 <span data-ttu-id="cf328-471">公共语言运行时 (CLR) 更新的堆栈跟踪，每当应用程序代码中引发异常时 (通过使用`throw`关键字)。</span><span class="sxs-lookup"><span data-stu-id="cf328-471">The common language runtime (CLR) updates the stack trace whenever an exception is thrown in application code (by using the `throw` keyword).</span></span> <span data-ttu-id="cf328-472">如果在方法的不同方法比最初引发异常时，堆栈跟踪包含其中最初引发异常，方法中的位置和方法中的位置，其中的异常为再次引发。</span><span class="sxs-lookup"><span data-stu-id="cf328-472">If the exception was rethrown in a method that is different than the method where it was originally thrown, the stack trace contains both the location in the method where the exception was originally thrown, and the location in the method where the exception was rethrown.</span></span> <span data-ttu-id="cf328-473">如果引发，并且稍后再次引发异常的情况下，在同一方法中，异常堆栈跟踪仅包含的位置重新引发异常并不包括最初引发异常的位置。</span><span class="sxs-lookup"><span data-stu-id="cf328-473">If the exception is thrown, and later rethrown, in the same method, the stack trace only contains the location where the exception was rethrown and does not include the location where the exception was originally thrown.</span></span>  
  
 <span data-ttu-id="cf328-474"><xref:System.Exception.StackTrace%2A>属性可能不会报告任意多个方法调用如预期，因为代码转换为内联，优化过程中发生的。</span><span class="sxs-lookup"><span data-stu-id="cf328-474">The <xref:System.Exception.StackTrace%2A> property may not report as many method calls as expected because of code transformations, such as inlining, that occur during optimization.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-475">下面的代码示例，则会引发`Exception`捕捉该异常并显示堆栈跟踪使用`StackTrace`属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-475">The following code example throws an `Exception` and then catches it and displays a stack trace using the `StackTrace` property.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides"><para><span data-ttu-id="cf328-476"><see langword="StackTrace" />需要控制堆栈跟踪内容或格式的类中重写属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-476">The <see langword="StackTrace" /> property is overridden in classes that require control over the stack trace content or format.</span></span>  
  
<span data-ttu-id="cf328-477">默认情况下，堆栈跟踪被捕获之前引发的异常对象。</span><span class="sxs-lookup"><span data-stu-id="cf328-477">By default, the stack trace is captured immediately before an exception object is thrown.</span></span> <span data-ttu-id="cf328-478">使用<see cref="P:System.Environment.StackTrace" />会不引发任何异常时获取堆栈跟踪信息。</span><span class="sxs-lookup"><span data-stu-id="cf328-478">Use <see cref="P:System.Environment.StackTrace" /> to get stack trace information when no exception is being thrown.</span></span></para></block>
        <altmember cref="P:System.Environment.StackTrace" />
      </Docs>
    </Member>
    <Member MemberName="TargetSite">
      <MemberSignature Language="C#" Value="public System.Reflection.MethodBase TargetSite { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Reflection.MethodBase TargetSite" />
      <MemberSignature Language="DocId" Value="P:System.Exception.TargetSite" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property TargetSite As MethodBase" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property System::Reflection::MethodBase ^ TargetSite { System::Reflection::MethodBase ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.TargetSite : System.Reflection.MethodBase" Usage="System.Exception.TargetSite" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.TargetSite</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
          <AttributeName>get: System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Reflection.MethodBase</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="cf328-479">获取引发当前异常的方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-479">Gets the method that throws the current exception.</span></span></summary>
        <value><span data-ttu-id="cf328-480">引发当前异常的 <see cref="T:System.Reflection.MethodBase" />。</span><span class="sxs-lookup"><span data-stu-id="cf328-480">The <see cref="T:System.Reflection.MethodBase" /> that threw the current exception.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-481">如果会引发此异常的方法不可用并且堆栈跟踪不是 null 引用 (`Nothing`在 Visual Basic 中)，<xref:System.Exception.TargetSite%2A>从堆栈跟踪获取该方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-481">If the method that throws this exception is not available and the stack trace is not a null reference (`Nothing` in Visual Basic), <xref:System.Exception.TargetSite%2A> obtains the method from the stack trace.</span></span> <span data-ttu-id="cf328-482">如果堆栈跟踪为空引用，<xref:System.Exception.TargetSite%2A> 也返回空引用。</span><span class="sxs-lookup"><span data-stu-id="cf328-482">If the stack trace is a null reference, <xref:System.Exception.TargetSite%2A> also returns a null reference.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="cf328-483"><xref:System.Exception.TargetSite%2A>属性可能无法准确报告中如果异常处理程序处理的异常跨应用程序域边界引发异常的方法的名称。</span><span class="sxs-lookup"><span data-stu-id="cf328-483">The <xref:System.Exception.TargetSite%2A> property may not accurately report the name of the method in which an exception was thrown if the exception handler handles an exception across application domain boundaries.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-484">下面的代码示例，则会引发`Exception`捕捉该异常并显示原始的方法使用`TargetSite`属性。</span><span class="sxs-lookup"><span data-stu-id="cf328-484">The following code example throws an `Exception` and then catches it and displays the originating method using the `TargetSite` property.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="ToString">
      <MemberSignature Language="C#" Value="public override string ToString ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig virtual instance string ToString() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.ToString" />
      <MemberSignature Language="VB.NET" Value="Public Overrides Function ToString () As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; override System::String ^ ToString();" />
      <MemberSignature Language="F#" Value="override this.ToString : unit -&gt; string" Usage="exception.ToString " />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.ToString</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="cf328-485">创建并返回当前异常的字符串表示形式。</span><span class="sxs-lookup"><span data-stu-id="cf328-485">Creates and returns a string representation of the current exception.</span></span></summary>
        <returns><span data-ttu-id="cf328-486">当前异常的字符串表示形式。</span><span class="sxs-lookup"><span data-stu-id="cf328-486">A string representation of the current exception.</span></span></returns>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="cf328-487"><xref:System.Exception.ToString%2A> 返回用于为人所理解的当前异常的表示形式。</span><span class="sxs-lookup"><span data-stu-id="cf328-487"><xref:System.Exception.ToString%2A> returns a representation of the current exception that is intended to be understood by humans.</span></span> <span data-ttu-id="cf328-488">当该异常包含区分区域性的数据，返回的字符串表示形式`ToString`所需的当前系统区域性考虑在内。</span><span class="sxs-lookup"><span data-stu-id="cf328-488">Where the exception contains culture-sensitive data, the string representation returned by `ToString` is required to take into account the current system culture.</span></span> <span data-ttu-id="cf328-489">虽然没有返回字符串的确切格式要求，但它应尝试反映形式从用户的角度的对象的值。</span><span class="sxs-lookup"><span data-stu-id="cf328-489">Although there are no exact requirements for the format of the returned string, it should attempt to reflect the value of the object as perceived by the user.</span></span>  
  
 <span data-ttu-id="cf328-490">默认实现<xref:System.Exception.ToString%2A>获取引发当前异常、 消息、 调用的结果的类的名称<xref:System.Exception.ToString%2A>上的内部异常，并因调用<xref:System.Environment.StackTrace%2A?displayProperty=nameWithType>。</span><span class="sxs-lookup"><span data-stu-id="cf328-490">The default implementation of <xref:System.Exception.ToString%2A> obtains the name of the class that threw the current exception, the message, the result of calling <xref:System.Exception.ToString%2A> on the inner exception, and the result of calling <xref:System.Environment.StackTrace%2A?displayProperty=nameWithType>.</span></span> <span data-ttu-id="cf328-491">如果任何这些成员为`null`，其值不包括在返回的字符串。</span><span class="sxs-lookup"><span data-stu-id="cf328-491">If any of these members is `null`, its value is not included in the returned string.</span></span>  
  
 <span data-ttu-id="cf328-492">如果没有任何错误消息或为空字符串 ("")，则不返回任何错误消息。</span><span class="sxs-lookup"><span data-stu-id="cf328-492">If there is no error message or if it is an empty string (""), then no error message is returned.</span></span> <span data-ttu-id="cf328-493">仅当它们不是返回的内部异常和堆栈跟踪名称`null`。</span><span class="sxs-lookup"><span data-stu-id="cf328-493">The name of the inner exception and the stack trace are returned only if they are not `null`.</span></span>  
  
 <span data-ttu-id="cf328-494">此方法重写 <xref:System.Object.ToString%2A?displayProperty=nameWithType>。</span><span class="sxs-lookup"><span data-stu-id="cf328-494">This method overrides <xref:System.Object.ToString%2A?displayProperty=nameWithType>.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="cf328-495">下面的示例会导致异常，并显示调用的结果<xref:System.Exception.ToString%2A>上该异常。</span><span class="sxs-lookup"><span data-stu-id="cf328-495">The following example causes an exception and displays the result of calling <xref:System.Exception.ToString%2A> on that exception.</span></span> <span data-ttu-id="cf328-496">请注意，<xref:System.Exception.ToString%2A?displayProperty=nameWithType>的参数列表中出现的异常类实例时，方法隐式调用<xref:System.Console.WriteLine%2A?displayProperty=nameWithType>方法。</span><span class="sxs-lookup"><span data-stu-id="cf328-496">Note that the <xref:System.Exception.ToString%2A?displayProperty=nameWithType> method is called implicitly when the Exception class instance appears in the argument list of the <xref:System.Console.WriteLine%2A?displayProperty=nameWithType> method.</span></span>  
  
 [!code-cpp[System.Exception.ToString#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.exception.tostring/cpp/ToStringEx1.cpp#1)]
 [!code-csharp[System.Exception.ToString#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.tostring/cs/ToStringEx1.cs#1)]
 [!code-vb[System.Exception.ToString#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.tostring/vb/ToStringEx1.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>