<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="HttpException.xml" source-language="en-US" target-language="zh-CN">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac51864e8fe52f0eb87b7c23fbfe505d15cf9681ede.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1864e8fe52f0eb87b7c23fbfe505d15cf9681ede</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Web.HttpException">
          <source>Describes an exception that occurred during the processing of HTTP requests.</source>
          <target state="translated">描述在处理 HTTP 请求期间发生的异常。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>The <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> class is an HTTP-specific exception class that enables ASP.NET to generate exception information.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>类是使 ASP.NET 生成异常信息的 HTTP 特定异常类。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>For more information about throwing and handling exceptions, see <bpt id="p1">[</bpt>Exceptions<ept id="p1">](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)</ept>.</source>
          <target state="translated">有关引发和处理异常的详细信息，请参阅<bpt id="p1">[</bpt>异常<ept id="p1">](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)</ept>。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>The following code example demonstrates how to use the <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> class to raise customized exceptions.</source>
          <target state="translated">下面的代码示例演示如何使用<ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>类引发自定义的异常。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>The <ph id="ph1">`Button_Click`</ph> method determines which button was clicked, and then calls either the <ph id="ph2">`CheckNumber`</ph> or <ph id="ph3">`CheckBoolean`</ph> method.</source>
          <target state="translated"><ph id="ph1">`Button_Click`</ph>方法确定哪个按钮被单击，然后调用是<ph id="ph2">`CheckNumber`</ph>或<ph id="ph3">`CheckBoolean`</ph>方法。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>If the user-entered value in the text box does not correspond to the expected type, an <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> exception is created and thrown with a customized message based on the error type.</source>
          <target state="translated">如果在文本框中的用户输入的值不对应于预期的类型，<ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>创建并与基于错误类型的自定义消息引发异常。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">此示例具有一个接受用户输入的文本框，这是一个潜在的安全威胁。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">默认情况下，ASP.NET 网页验证用户输入是否不包含脚本或 HTML 元素。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>脚本侵入概述<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="T:System.Web.HttpException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class and creates an empty <ph id="ph2">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> object.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 类的新实例并创建一个空 <ph id="ph2">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 对象。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.</source>
          <target state="translated">当处理异常时，它可用于捕获一系列相关与外部异常因响应内部异常引发的异常。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>A reference to the inner exception that caused the outer exception is available from the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property of the outer exception.</source>
          <target state="translated">对导致外部异常的内部异常的引用位于<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>外部异常的属性。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.</source>
          <target state="translated">此机制保留早期的异常，包括原始异常，同时使你可以创建更有意义的外部异常携带的错误信息。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>For more information, see <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</source>
          <target state="translated">有关详情，请参阅<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">下面的代码示例演示<ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph>构造函数的<ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph>类。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>The <ph id="ph1">`CheckNumber`</ph> method accepts a user-entered value through a text box and checks whether it is an integer.</source>
          <target state="translated"><ph id="ph1">`CheckNumber`</ph>方法接受用户输入的值，通过在文本框中，并检查它是否为整数。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>If the value is not an integer, an exception is thrown, and then a new <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object is created and thrown.</source>
          <target state="translated">如果值不是一个整数，则引发异常，和一个新<ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>创建并引发对象。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>That exception is caught in the <ph id="ph1">`Button_Click`</ph> event handler and the error message is displayed on the browser.</source>
          <target state="translated">中捕获到异常<ph id="ph1">`Button_Click`</ph>事件处理程序和错误消息显示在浏览器。</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">此示例具有一个接受用户输入的文本框，这是一个潜在的安全威胁。</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">默认情况下，ASP.NET 网页验证用户输入是否不包含脚本或 HTML 元素。</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>脚本侵入概述<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">当发生异常时向客户端显示的错误消息。</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using a supplied error message.</source>
          <target state="translated">使用所提供的错误消息初始化 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">下面的代码示例演示<ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph>构造函数的<ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph>类。</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>An <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> is thrown if a user-entered value is 0.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>如果用户输入的值为 0，将引发。</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">此示例具有一个接受用户输入的文本框，这是一个潜在的安全威胁。</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">默认情况下，ASP.NET 网页验证用户输入是否不包含脚本或 HTML 元素。</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>脚本侵入概述<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>。</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String)">
          <source>The HTTP response status code sent to the client corresponding to this error.</source>
          <target state="translated">发送到对应于此错误的客户端的 HTTP 响应状态代码。</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">当发生异常时向客户端显示的错误消息。</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an HTTP response status code and an error message.</source>
          <target state="translated">使用 HTTP 响应状态代码和错误消息初始化 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> that holds the serialized object data about the exception being thrown.</source>
          <target state="translated">包含有关所引发异常的序列化对象数据的 <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> that holds the contextual information about the source or destination.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>，它包含有关源或目标的上下文信息。</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">用序列化数据初始化 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph>反序列化，以便重建通过流传输的异常对象期间调用构造函数。</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>XML 和 SOAP 序列化<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>。</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">当发生异常时向客户端显示的错误消息。</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>, if any, that threw the current exception.</source>
          <target state="translated">引发当前异常的 <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>（如果有的话）。</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an error message and the <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> property.</source>
          <target state="translated">使用错误消息和 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 属性初始化 <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="141" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.</source>
          <target state="translated">当处理异常时，它可用于捕获一系列相关与外部异常因响应内部异常引发的异常。</target>       </trans-unit>
        <trans-unit id="142" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>A reference to the inner exception that caused the outer exception is available from the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property of the outer exception.</source>
          <target state="translated">对导致外部异常的内部异常的引用位于<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>外部异常的属性。</target>       </trans-unit>
        <trans-unit id="143" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.</source>
          <target state="translated">此机制保留早期的异常，包括原始异常，同时使你可以创建更有意义的外部异常携带的错误信息。</target>       </trans-unit>
        <trans-unit id="144" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>For more information, see <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</source>
          <target state="translated">有关详情，请参阅<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="145" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">下面的代码示例演示<ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph>构造函数的<ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph>类。</target>       </trans-unit>
        <trans-unit id="146" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">`CheckNumber`</ph> method accepts a user-entered value through a text box and checks whether it is an integer.</source>
          <target state="translated"><ph id="ph1">`CheckNumber`</ph>方法接受用户输入的值，通过在文本框中，并检查它是否为整数。</target>       </trans-unit>
        <trans-unit id="147" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>If the value is not an integer, an exception is thrown, and then in the catch block, a new <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object is created and thrown.</source>
          <target state="translated">如果值不是一个整数，则引发异常，然后在 catch 块中，新<ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>创建并引发对象。</target>       </trans-unit>
        <trans-unit id="148" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>That exception is caught in the <ph id="ph1">`Button_Click`</ph> event handler and the error message is displayed on the browser.</source>
          <target state="translated">中捕获到异常<ph id="ph1">`Button_Click`</ph>事件处理程序和错误消息显示在浏览器。</target>       </trans-unit>
        <trans-unit id="149" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">此示例具有一个接受用户输入的文本框，这是一个潜在的安全威胁。</target>       </trans-unit>
        <trans-unit id="150" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">默认情况下，ASP.NET 网页验证用户输入是否不包含脚本或 HTML 元素。</target>       </trans-unit>
        <trans-unit id="151" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>脚本侵入概述<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>。</target>       </trans-unit>
        <trans-unit id="152" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">当发生异常时向客户端显示的错误消息。</target>       </trans-unit>
        <trans-unit id="153" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>The exception code that defines the error.</source>
          <target state="translated">定义错误的异常代码。</target>       </trans-unit>
        <trans-unit id="154" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an error message and an exception code.</source>
          <target state="translated">使用错误消息和异常代码初始化 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="155" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">下面的代码示例演示<ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph>构造函数的<ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph>类。</target>       </trans-unit>
        <trans-unit id="156" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>An <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> exception is thrown if a user-entered value is 0.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>如果用户输入的值为 0 将引发异常。</target>       </trans-unit>
        <trans-unit id="157" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">此示例具有一个接受用户输入的文本框，这是一个潜在的安全威胁。</target>       </trans-unit>
        <trans-unit id="158" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">默认情况下，ASP.NET 网页验证用户输入是否不包含脚本或 HTML 元素。</target>       </trans-unit>
        <trans-unit id="159" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>脚本侵入概述<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>。</target>       </trans-unit>
        <trans-unit id="160" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The HTTP response status code displayed on the client.</source>
          <target state="translated">在客户端上显示的 HTTP 响应状态代码。</target>       </trans-unit>
        <trans-unit id="161" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">当发生异常时向客户端显示的错误消息。</target>       </trans-unit>
        <trans-unit id="162" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>, if any, that threw the current exception.</source>
          <target state="translated">引发当前异常的 <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>（如果有的话）。</target>       </trans-unit>
        <trans-unit id="163" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an HTTP response status code, an error message, and the <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> property.</source>
          <target state="translated">使用 HTTP 响应状态代码、错误消息以及 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 属性初始化 <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="164" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.</source>
          <target state="translated">当处理异常时，它可用于捕获一系列相关与外部异常因响应内部异常引发的异常。</target>       </trans-unit>
        <trans-unit id="165" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>A reference to the inner exception that caused the outer exception is available from the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property of the outer exception.</source>
          <target state="translated">对导致外部异常的内部异常的引用位于<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>外部异常的属性。</target>       </trans-unit>
        <trans-unit id="166" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.</source>
          <target state="translated">此机制保留早期的异常，包括原始异常，同时使你可以创建更有意义的外部异常携带的错误信息。</target>       </trans-unit>
        <trans-unit id="167" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>For more information, see <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</source>
          <target state="translated">有关详情，请参阅<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="168" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">下面的代码示例演示<ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph>构造函数的<ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph>类。</target>       </trans-unit>
        <trans-unit id="169" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The <ph id="ph1">`CheckNumber`</ph> method accepts a user-entered value and checks whether it is an integer.</source>
          <target state="translated"><ph id="ph1">`CheckNumber`</ph>方法接受用户输入的值，并检查它是否为整数。</target>       </trans-unit>
        <trans-unit id="170" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>If the value is not an integer, an exception is thrown, and then a new <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object containing the HTTP response status code, the exception's message, and any inner exception is created.</source>
          <target state="translated">如果值不是一个整数，则引发异常，和一个新<ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>创建对象，其中包含 HTTP 响应状态代码、 异常的消息和任何内部异常。</target>       </trans-unit>
        <trans-unit id="171" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>That exception is caught in the <ph id="ph1">`Button_Click`</ph> event handler and the error message, error code, and inner exception are displayed.</source>
          <target state="translated">中捕获到异常<ph id="ph1">`Button_Click`</ph>显示事件处理程序的错误消息、 错误代码和内部异常。</target>       </trans-unit>
        <trans-unit id="172" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">此示例具有一个接受用户输入的文本框，这是一个潜在的安全威胁。</target>       </trans-unit>
        <trans-unit id="173" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">默认情况下，ASP.NET 网页验证用户输入是否不包含脚本或 HTML 元素。</target>       </trans-unit>
        <trans-unit id="174" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>脚本侵入概述<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>。</target>       </trans-unit>
        <trans-unit id="175" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The HTTP response status code displayed on the client.</source>
          <target state="translated">在客户端上显示的 HTTP 响应状态代码。</target>       </trans-unit>
        <trans-unit id="176" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">当发生异常时向客户端显示的错误消息。</target>       </trans-unit>
        <trans-unit id="177" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The exception code that defines the error.</source>
          <target state="translated">定义错误的异常代码。</target>       </trans-unit>
        <trans-unit id="178" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an HTTP response status code, an error message, and an exception code.</source>
          <target state="translated">使用 HTTP 响应状态代码、错误消息和异常代码初始化 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="179" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">下面的代码示例演示<ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph>构造函数的<ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph>类。</target>       </trans-unit>
        <trans-unit id="180" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The user name and email information are entered by the user in the provided text boxes.</source>
          <target state="translated">用户在提供的文本框中输入用户名和电子邮件信息。</target>       </trans-unit>
        <trans-unit id="181" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>If any of the text boxes are left blank, an <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object is created and thrown.</source>
          <target state="translated">如果任何文本框留空，<ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>创建并引发对象。</target>       </trans-unit>
        <trans-unit id="182" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The error code of the <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> is obtained by the <ph id="ph2">&lt;xref:System.Web.HttpException.GetHttpCode%2A&gt;</ph> method and displayed on the Web page.</source>
          <target state="translated">错误代码的<ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph>通过获取<ph id="ph2">&lt;xref:System.Web.HttpException.GetHttpCode%2A&gt;</ph>方法并在网页上显示。</target>       </trans-unit>
        <trans-unit id="183" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">此示例具有一个接受用户输入的文本框，这是一个潜在的安全威胁。</target>       </trans-unit>
        <trans-unit id="184" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">默认情况下，ASP.NET 网页验证用户输入是否不包含脚本或 HTML 元素。</target>       </trans-unit>
        <trans-unit id="185" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>脚本侵入概述<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>。</target>       </trans-unit>
        <trans-unit id="186" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.CreateFromLastError(System.String)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">当发生异常时向客户端显示的错误消息。</target>       </trans-unit>
        <trans-unit id="187" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.CreateFromLastError(System.String)">
          <source>Creates a new <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> exception based on the error code that is returned from the Win32 API <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> method.</source>
          <target state="translated">基于从 Win32 API <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> 方法返回的错误代码创建一个新的 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> 异常。</target>       </trans-unit>
        <trans-unit id="188" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.CreateFromLastError(System.String)">
          <source>An <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> based on the error code that is returned from a call to the Win32 API <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> method.</source>
          <target state="translated">一个 <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>，它基于从对 Win32 API <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> 方法的调用返回的错误代码。</target>       </trans-unit>
        <trans-unit id="189" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHtmlErrorMessage">
          <source>Gets the HTML error message to return to the client.</source>
          <target state="translated">获取要返回给客户端的 HTML 错误消息。</target>       </trans-unit>
        <trans-unit id="190" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHtmlErrorMessage">
          <source>The HTML error message.</source>
          <target state="translated">HTML 错误消息。</target>       </trans-unit>
        <trans-unit id="191" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHttpCode">
          <source>Gets the HTTP response status code to return to the client.</source>
          <target state="translated">获取要返回给客户端的 HTTP 响应状态代码。</target>       </trans-unit>
        <trans-unit id="192" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHttpCode">
          <source>A non-zero HTTP code representing the exception or the <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> code; otherwise, HTTP response status code 500.</source>
          <target state="translated">表示异常或 <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> 代码的非零 HTTP 代码；否则为 HTTP 响应状态代码 500。</target>       </trans-unit>
        <trans-unit id="193" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>If there is a non-zero HTTP code, it is returned.</source>
          <target state="translated">如果非零 HTTP 代码，它将返回。</target>       </trans-unit>
        <trans-unit id="194" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>Otherwise, the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> code is returned.</source>
          <target state="translated">否则为<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>返回代码。</target>       </trans-unit>
        <trans-unit id="195" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>If neither an <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> code nor a non-zero HTTP code is available, the HTTP response status code 500 is returned.</source>
          <target state="translated">如果既没有<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>代码和非零 HTTP 代码为可用，则返回 HTTP 响应状态代码 500。</target>       </trans-unit>
        <trans-unit id="196" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>For more information on HTTP response status codes, see the Status Code Definitions of the Hypertext Transfer Protocol - HTTP/1.1 on the World <bpt id="p1">[</bpt>Wide Web Consortium (W3C) Web site<ept id="p1">](http://go.microsoft.com/fwlink/?linkid=37125)</ept>.</source>
          <target state="translated">HTTP 响应状态代码的详细信息，请参阅超文本传输协议的世界上的 HTTP/1.1 状态代码定义<bpt id="p1">[</bpt>宽万维网联合会 (W3C) 网站<ept id="p1">](http://go.microsoft.com/fwlink/?linkid=37125)</ept>。</target>       </trans-unit>
        <trans-unit id="197" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> that holds the serialized object data about the exception being thrown.</source>
          <target state="translated">包含有关所引发异常的序列化对象数据的 <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="198" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> that holds the contextual information about the source or destination.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>，它包含有关源或目标的上下文信息。</target>       </trans-unit>
        <trans-unit id="199" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Gets information about the exception and adds it to the <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> object.</source>
          <target state="translated">获取关于异常的信息并将其添加到 <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> 对象。</target>       </trans-unit>
        <trans-unit id="200" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;xref:System.Web.HttpException.GetObjectData%2A&gt;</ph> method adds information about the exception to the <ph id="ph2">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> object that is targeted for serialization.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException.GetObjectData%2A&gt;</ph>方法将添加到异常有关的信息<ph id="ph2">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph>针对于序列化的对象。</target>       </trans-unit>
        <trans-unit id="201" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>During deserialization, the exception is reconstituted from the <ph id="ph1">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> that is transmitted over the stream.</source>
          <target state="translated">在反序列化期间重建异常从<ph id="ph1">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph>通过流传输。</target>       </trans-unit>
        <trans-unit id="202" translate="yes" xml:space="preserve" uid="P:System.Web.HttpException.WebEventCode">
          <source>Gets the event codes that are associated with the HTTP exception.</source>
          <target state="translated">获取与 HTTP 异常相关联的事件代码。</target>       </trans-unit>
        <trans-unit id="203" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.HttpException.WebEventCode">
          <source>An integer representing a Web event code.</source>
          <target state="translated">一个表示 Web 事件代码的整数。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>